UPDATE plan_data_exchange_approach
SET
  model_plan_id = :model_plan_id,
  data_to_collect_from_participants = :data_to_collect_from_participants,
  data_to_collect_from_participants_reports_details = :data_to_collect_from_participants_reports_details,
  data_to_collect_from_participants_other = :data_to_collect_from_participants_other,
  data_will_not_be_collected_from_participants = :data_will_not_be_collected_from_participants,
  data_to_collect_from_participants_note = :data_to_collect_from_participants_note,
  data_to_send_to_participants = :data_to_send_to_participants,
  data_to_send_to_participants_note = :data_to_send_to_participants_note,
  does_need_to_make_multi_payer_data_available = :does_need_to_make_multi_payer_data_available,
  anticipated_multi_payer_data_availability_use_case = :anticipated_multi_payer_data_availability_use_case,
  does_need_to_make_multi_payer_data_available_other = :does_need_to_make_multi_payer_data_available_other,
  does_need_to_make_multi_payer_data_available_note = :does_need_to_make_multi_payer_data_available_note,
  does_need_to_collect_and_aggregate_multi_source_data = :does_need_to_collect_and_aggregate_multi_source_data,
  multi_source_data_to_collect = :multi_source_data_to_collect,
  multi_source_data_to_collect_other = :multi_source_data_to_collect_other,
  does_need_to_collect_and_aggregate_multi_source_data_note = :does_need_to_collect_and_aggregate_multi_source_data_note,
  will_implement_new_data_exchange_methods = :will_implement_new_data_exchange_methods,
  new_data_exchange_methods_description = :new_data_exchange_methods_description,
  new_data_exchange_methods_note = :new_data_exchange_methods_note,
  additional_data_exchange_considerations_description = :additional_data_exchange_considerations_description,
  is_data_exchange_approach_complete = :is_data_exchange_approach_complete,
  modified_by = :modified_by,
  modified_dts = CURRENT_TIMESTAMP
WHERE id = :id
RETURNING
  id,
  model_plan_id,
  data_to_collect_from_participants,
  data_to_collect_from_participants_reports_details,
  data_to_collect_from_participants_other,
  data_will_not_be_collected_from_participants,
  data_to_collect_from_participants_note,
  data_to_send_to_participants,
  data_to_send_to_participants_note,
  does_need_to_make_multi_payer_data_available,
  anticipated_multi_payer_data_availability_use_case,
  does_need_to_make_multi_payer_data_available_note,
  does_need_to_collect_and_aggregate_multi_source_data,
  multi_source_data_to_collect,
  multi_source_data_to_collect_other,
  does_need_to_collect_and_aggregate_multi_source_data_note,
  will_implement_new_data_exchange_methods,
  new_data_exchange_methods_description,
  new_data_exchange_methods_note,
  additional_data_exchange_considerations_description,
  is_data_exchange_approach_complete,
  created_by,
  created_dts,
  modified_by,
  modified_dts;
