version: "2"
run:
  concurrency: 1
linters:
  enable:
    - exhaustive
    - gosec
    - revive
    - sqlclosecheck
    - staticcheck
  disable:
    - errcheck
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gosec:
      excludes:
        - G602
    govet:
      enable:
        - shadow
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    revive:
      confidence: 0.1
  exclusions:
    generated: disable
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "err" shadows declaration at'
      - path: (.+)\.go$
        text: ST1000
    paths:
      - pkg/graph/generated/generated.go
      - pkg/graph/model/models_gen.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/cms-enterprise/mint-app
  exclusions:
    generated: disable
    paths:
      - pkg/graph/generated/generated.go # Since we don't ignore _all_ generated files, we have to ignore this one specifically
      - pkg/graph/model/models_gen.go # Since we don't ignore _all_ generated files, we have to ignore this one specifically
      - third_party$
      - builtin$
      - examples$
