linters-settings:
  gosec:
    # Currently excluding rule G602 due to issue slowing down execution
    # https://github.com/securego/gosec/issues/1010
    # If we ever re-enable this rule, make sure https://github.com/securego/gosec/issues/1005 is also fixed
    excludes:
      - "G602"
  govet:
    enable:
      - shadow
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/cms-enterprise/mint-app
  revive:
    confidence: 0.1 # Default is 0.8. We want to ignore things that have an extremely low confidence level
  exhaustive:
    # Presence of "default" case in switch statements satisfies exhaustiveness,
    # even if all enum members are not listed.
    # Default: false
    default-signifies-exhaustive: true


linters:
  enable:
     - gosec
     - gofmt
     - goimports
     - govet
     - typecheck
     - ineffassign
     - revive
     - staticcheck
     - stylecheck
     - gosimple #will be deprecated in golangci-lint v2.0 in favor of staticcheck https://github.com/golangci/golangci-lint/issues/357
     - unused #will be deprecated in golangci-lint v2.0 in favor of staticcheck https://github.com/golangci/golangci-lint/issues/357
     - exhaustive
     - sqlclosecheck
  disable:
    - errcheck #requires patching code
issues:
  exclude-use-default: false
  exclude:
    - "ST1000" # Exclude package comments from `stylecheck`
  exclude-files:
    - "pkg/graph/generated/generated.go" # Since we don't ignore _all_ generated files, we have to ignore this one specifically
    - "pkg/graph/model/models_gen.go" # Since we don't ignore _all_ generated files, we have to ignore this one specifically
  exclude-rules:
    - text: 'shadow: declaration of "err" shadows declaration at'
      linters: [ govet ]
  exclude-generated: disable

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 8m
  concurrency: 1
