FROM node:16.14.0 AS base

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

FROM base AS modules

COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile

FROM modules AS src

COPY craco.config.js ./
COPY tsconfig.json ./
COPY .eslintrc ./
COPY public ./public
COPY src ./src

ENTRYPOINT [ "yarn", "start" ]
