ARG TAG=
FROM flyway/flyway:${TAG}

COPY migrations/ /flyway/sql

ENV FLYWAY_CONNECT_RETRIES=10
ENV FLYWAY_CLEAN_DISABLED="true"
ENV FLYWAY_SCHEMAS=public
ENV FLYWAY_DEFAULT_SCHEMA=public

ENTRYPOINT ["flyway", "-validateMigrationNaming=true", "migrate" ]
