---
version: '3.7'
services:
  db:
    image: postgres:11.12
    command: ['postgres', '-c', 'log_statement=all', '-c', 'max_connections=25']
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  db_migrate:
    image: easi-db-migrate:latest
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=mysecretpassword
      - FLYWAY_URL=jdbc:postgresql://db/postgres
      - FLYWAY_PLACEHOLDERS_APP_USER_PASSWORD=supersecretapp
    depends_on:
      - db
  easi:
    environment:
      - CEDAR_API_KEY
      - CEDAR_API_URL
      - HTTP_PROXY
      - HTTPS_PROXY
      - APP_ENV
      - APPLICATION_VERSION
      - APPLICATION_DATETIME
      - APPLICATION_TS
      - CLIENT_PROTOCOL=http
      - CLIENT_DOMAIN=localhost
      - CLIENT_PORT=3000
      - CLIENT_HOSTNAME=localhost:3000
      - CLIENT_ADDRESS=http://localhost:3000
      - API_PORT=8080
      - OKTA_CLIENT_ID=0oa2e913coDQeG19S297
      - OKTA_ISSUER=https://test.idp.idm.cms.gov/oauth2/aus2e96etlbFPnBHt297
      - GRT_EMAIL=success@simulator.amazonses.com
      - ACCESSIBILITY_TEAM_EMAIL=success@simluator.amazonses.com
      - EMAIL_TEMPLATE_DIR=./pkg/email/templates
      - AWS_REGION=us-west-2
      - AWS_SES_SOURCE=no-reply-$APP_ENV@info.easi.cms.gov
      - AWS_SES_SOURCE_ARN
      - AWS_S3_FILE_UPLOAD_BUCKET=easi-app-file-uploads
      - AWS_ACCESS_KEY_ID=1
      - AWS_SECRET_ACCESS_KEY=1
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=app_user
      - PGPASS=supersecretapp
      - PGSSLMODE=disable
      - DB_MAX_CONNECTIONS=20
      - FLAG_SOURCE
      - LD_SDK_KEY
      - LD_TIMEOUT_SECONDS=30
      - LD_ENV_USER
      - LAMBDA_FUNCTION_PRINCE=handler
      - LAMBDA_ENDPOINT=http://prince:9001
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_ADDRESS=http://minio:9000
      - SERVER_CERT
      - SERVER_KEY
      - USE_TLS
    depends_on:
      - db_migrate
  easi_client:
    image: easi-frontend:latest
  minio:
    restart: always
    image: minio/minio:latest
    entrypoint: minio server /data
  minio_mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rb --force local/easi-app-file-uploads/;
      /usr/bin/mc mb --quiet local/easi-app-file-uploads/;
      /usr/bin/mc policy set public local/easi-app-file-uploads;
      "
