---
version: '3.7'
services:
  db:
    image: postgres:14.4
    command: ['postgres', '-c', 'log_statement=all', '-c', 'max_connections=25']
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  db_migrate:
    image: mint-db-migrate:latest
    platform: linux/amd64
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=mysecretpassword
      - FLYWAY_URL=jdbc:postgresql://db/postgres
      - FLYWAY_PLACEHOLDERS_APP_USER_PASSWORD=supersecretapp

    depends_on:
      - db
  mint:
    environment:
      - CEDAR_API_KEY
      - CEDAR_API_URL
      - OKTA_API_URL
      - OKTA_API_TOKEN
      - HTTP_PROXY
      - HTTPS_PROXY
      - APP_ENV
      - APPLICATION_VERSION
      - APPLICATION_DATETIME
      - APPLICATION_TS
      - CLIENT_PROTOCOL=http
      - CLIENT_DOMAIN=localhost
      - CLIENT_PORT=3005
      - CLIENT_HOSTNAME=localhost:3005
      - CLIENT_ADDRESS=http://localhost:3005
      - API_PORT=8080
      - OKTA_CLIENT_ID=0oad9awvebnsMwWNa297
      - OKTA_ISSUER=https://test.idp.idm.cms.gov/oauth2/ausd980kt2CBBzStG297
      - EMAIL_HOST=email
      - EMAIL_PORT=1025
      - MINT_TEAM_EMAIL
      - EMAIL_SENDER
      - EMAIL_ENABLED
      - GRT_EMAIL=success@simulator.amazonses.com
      - ACCESSIBILITY_TEAM_EMAIL=success@simluator.amazonses.com
      - EMAIL_TEMPLATE_DIR=./pkg/email/templates
      - AWS_REGION=us-west-2
      - AWS_S3_FILE_UPLOAD_BUCKET=mint-app-file-uploads
      - AWS_ACCESS_KEY_ID=1
      - AWS_SECRET_ACCESS_KEY=1
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASS=mysecretpassword
      - PGSSLMODE=disable
      - DB_MAX_CONNECTIONS=20
      - FLAG_SOURCE
      - FLAGDATA_FILE
      - LD_SDK_KEY
      - LD_TIMEOUT_SECONDS=30
      - LD_ENV_USER
      - LAMBDA_FUNCTION_PRINCE=handler
      - LAMBDA_ENDPOINT=http://prince:9001
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_ADDRESS=http://minio:9005
      - SERVER_CERT
      - SERVER_KEY
      - USE_TLS
      - FAKTORY_URL
      - FAKTORY_PROCESS_JOBS
      - FAKTORY_CONNECTIONS

    depends_on:
      db_migrate:
        condition: service_completed_successfully # Only start if migrations completed successfully
  mint_client:
    image: mint-frontend:latest
  minio:
    restart: always
    image: minio/minio:latest
    entrypoint: minio server /data --console-address ":9966" --address ":9005"
  minio_mc:
    image: minio/mc:latest
    volumes:
      - ./minio_config.json:/root/.mc/config.json
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc rb --force s3local/mint-app-file-uploads/;
      /usr/bin/mc mb --quiet s3local/mint-app-file-uploads/;
      /usr/bin/mc policy set public s3local/mint-app-file-uploads;
      "
  email:
    image: dockage/mailcatcher:0.7.1
    platform: linux/amd64
    ports:
      - "1085:1080"
      - "1030:1025"
  faktory:
    image: docker.contribsys.com/contribsys/faktory-ent:latest
    ports:
      - 7419:7419
      - 7420:7420
    volumes:
      - faktory:/var/lib/faktory
      - type: bind
        source: ./.faktory/conf.d
        target: /root/.faktory/conf.d
    restart: always

  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.6.2"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esconfig:/usr/share/elasticsearch/config
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
      test: [ "CMD", "curl","-s" ,"-f", "-u", "${ES_USERNAME}:${ES_PASSWORD}", "http://localhost:9200/_cat/health" ]

volumes:
  faktory:
  esconfig:
  esdata:
