---
version: '3.7'
services:
  db:
    ports:
      - 5432:5432
  db_migrate:
    build:
      context: .
      dockerfile: Dockerfile.db_migrations
    volumes:
      - ./migrations:/flyway/sql
  db_seed:
    build:
      context: .
      dockerfile: Dockerfile.db_seed
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASS=mysecretpassword
      - PGSSLMODE=disable
      - DB_MAX_CONNECTIONS=20
  mint:
    build:
      context: .
      dockerfile: Dockerfile
    image: mint-backend:latest
    environment:
      - APP_ENV=test
      - EMAIL_TEMPLATE_DIR=/mint/templates
      - FLAG_SOURCE=LOCAL
      - LOCAL_AUTH_ENABLED=true
    ports:
      - 8080:8080
  mint_client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - REACT_APP_APP_ENV=test
        - REACT_APP_API_ADDRESS=http://mint:8080/api/v1
        - REACT_APP_GRAPHQL_ADDRESS=http://mint:8080/api/graph/query
        - REACT_APP_OKTA_CLIENT_ID
        - REACT_APP_OKTA_DOMAIN
        - REACT_APP_OKTA_ISSUER
        - REACT_APP_OKTA_REDIRECT_URI
        - REACT_APP_OKTA_SERVER_ID
        - REACT_APP_LOCAL_AUTH_ENABLED=true
    environment:
      - CI=true #https://github.com/facebook/create-react-app/issues/8688
    entrypoint: ['serve', '-s', '-l', '3000']
    ports:
      - 3000:3000
  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    image: mint-cypress:latest
    environment:
      - OKTA_TEST_USERNAME
      - OKTA_TEST_PASSWORD
      - OKTA_TEST_SECRET
      - REACT_APP_API_ADDRESS=http://mint:8080/api/v1
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MINIO_HOST=minio:9005
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASS=mysecretpassword
      - PGSSLMODE=disable
      - DB_MAX_CONNECTIONS=20
    network_mode: 'service:mint_client'
    volumes:
      - ./cypress:/cypress
    depends_on:
      - mint_client
