---
version: '3.7'
services:
  mint_client:
    image: mint-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.client
      target: src
    environment:
      - VITE_APP_ENV
      - VITE_API_ADDRESS
      - VITE_GRAPHQL_ADDRESS
      - VITE_OKTA_CLIENT_ID
      - VITE_OKTA_DOMAIN
      - VITE_OKTA_ISSUER
      - VITE_OKTA_REDIRECT_URI
      - VITE_OKTA_SERVER_ID
      - VITE_LD_ENV_USER
      - VITE_LD_USER_HASH
      - VITE_LD_CLIENT_ID
      - VITE_LOCAL_AUTH_ENABLED
      - VITE_BEACON_ID
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3005:3005
