ARG TAG=9.10
FROM flyway/flyway:${TAG}

COPY migrations/ /flyway/sql

ENV FLYWAY_CONNECT_RETRIES=10 \
    FLYWAY_CLEAN_DISABLED="true" \
    FLYWAY_SCHEMAS=public \
    FLYWAY_DEFAULT_SCHEMA=public

ENTRYPOINT ["flyway", "-validateMigrationNaming=true", "migrate"]
