UPDATE ctat_request
SET
    status = :status,
    assigned_admin = :assigned_admin,
    notes = :notes,
    resolution = :resolution,
    modified_by = :modified_by,
    modified_dts = CURRENT_TIMESTAMP
WHERE ctat_request.id = :id
RETURNING
    id,
    human_readable_id_number,
    requester,
    status,
    assigned_admin,
    notes,
    resolution,
    cmmi_group,
    cmmi_group_other,
    cmmi_division,
    cmmi_division_other,
    contract_activity_type,
    contract_activity_type_other,
    contract_name,
    contract_number,
    contract_type,
    contract_type_other,
    type_of_help_needed,
    type_of_help_needed_other,
    describe_help_needed,
    request_urgency,
    date_assistance_needed_by,
    created_by,
    created_dts,
    modified_by,
    modified_dts;
