UPDATE plan_basics
SET
    model_plan_id = :model_plan_id,
    demo_code = :demo_code,
    ams_model_id = :ams_model_id,
    model_category = :model_category,
    additional_model_categories = :additional_model_categories,
    cms_centers = :cms_centers,
    cmmi_groups = :cmmi_groups,
    model_type = :model_type,
    model_type_other = :model_type_other,
    problem = :problem,
    goal = :goal,
    test_interventions = :test_interventions,
    note = :note,
    modified_by = :modified_by,
    modified_dts = CURRENT_TIMESTAMP,
    ready_for_review_by = :ready_for_review_by,
    ready_for_review_dts = :ready_for_review_dts,
    ready_for_clearance_by = :ready_for_clearance_by,
    ready_for_clearance_dts = :ready_for_clearance_dts,
    status = :status
WHERE plan_basics.id = :id
RETURNING
    id,
    model_plan_id,
    demo_code,
    ams_model_id,
    model_category,
    additional_model_categories,
    cms_centers,
    cmmi_groups,
    model_type,
    model_type_other,
    problem,
    goal,
    test_interventions,
    note,
    created_by,
    created_dts,
    modified_by,
    modified_dts,
    ready_for_review_by,
    ready_for_review_dts,
    ready_for_clearance_by,
    ready_for_clearance_dts,
    status;
