path.data: /usr/share/elasticsearch/data
http.port: 9200

# Define a Watcher webhook action
watcher:
  webhook:
    http_method: POST
    url: "http://localhost:9200/logs-statetrace_dump/_bulk"
    body: "{{#toJson}}ctx.payload{{/toJson}}"
    headers:
      Content-Type: "application/json"

# Enable security features
xpack.security.enabled: true
xpack.security.enrollment.enabled: true

# Enable encryption for HTTP API client connections, such as Kibana, Logstash, and Agents
xpack.security.http.ssl:
  enabled: true
  keystore.path: certs/http.p12

# Enable encryption and mutual authentication between cluster nodes
xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  keystore.path: certs/transport.p12
  truststore.path: certs/transport.p12

# Create a new cluster with the current node only
# Additional nodes can still join the cluster later
cluster.initial_master_nodes: ["elasticsearch"]
