ALTER TYPE model_category ADD VALUE IF NOT EXISTS 'DISEASE_SPECIFIC_AND_EPISODIC';
ALTER TYPE model_category ADD VALUE IF NOT EXISTS 'STATE_BASED';
ALTER TYPE model_category ADD VALUE IF NOT EXISTS 'HEALTH_PLAN';
ALTER TYPE model_category ADD VALUE IF NOT EXISTS 'TO_BE_DETERMINED';

ALTER TABLE plan_basics ADD COLUMN additional_categories model_category[];
