CREATE TYPE MTO_FACILITATOR AS ENUM (
    'MODEL_TEAM',
    'MODEL_LEAD',
    'IT_LEAD',
    'SOLUTION_ARCHITECT',
    'IT_SYSTEM_PRODUCT_OWNER',
    'PARTICIPANTS',
    'APPLICATION_SUPPORT_CONTRACTOR',
    'IMPLEMENTATION_CONTRACTOR',
    'EVALUATION_CONTRACTOR',
    'QUALITY_MEASURES_DEVELOPMENT_CONTRACTOR',
    'LEARNING_CONTRACTOR',
    'MONITORING_CONTRACTOR',
    'CONTRACTING_OFFICERS_REPRESENTATIVE',
    'LEARNING_AND_DIFFUSION_GROUP',
    'RESEARCH_AND_RAPID_CYCLE_EVALUATION_GROUP',
    'OTHER',
    'DATA_ANALYTICS_CONTRACTOR',
    'MODEL_DATA_LEAD'
);

CREATE TYPE MTO_RISK_INDICATOR AS ENUM (
    'ON_TRACK',
    'OFF_TRACK',
    'AT_RISK'
);
