INSERT INTO "public"."mto_common_solution"("key","name","type","subject","filter_view")
VALUES
('INNOVATION','4innovation (4i)','OTHER','{LEARNING}','IDDOC'),
('ACO_OS','Accountable Care Organization - Operational System (ACO-OS)','OTHER','{LEARNING}','IDDOC'),
('APPS','Automated Plan Payment System (APPS)','OTHER','{LEARNING}',NULL),
('CDX','Centralized Data Exchange (CDX)','OTHER','{LEARNING}',NULL),
('CCW','Chronic Conditions Warehouse (CCW)','OTHER','{LEARNING}','CCW'),
('CMS_BOX','CMS Box','OTHER','{LEARNING}',NULL),
('CMS_QUALTRICS','CMS Qualtrics','OTHER','{LEARNING}',NULL),
('CBOSC','Consolidated Business Operations Support Center (CBOSC)','OTHER','{LEARNING}','CBOSC'),
('CONTRACTOR','Contractor','OTHER','{LEARNING}',NULL),
('CPI_VETTING','CPI Vetting','OTHER','{LEARNING}',NULL),
('CROSS_MODEL_CONTRACT','Cross-model contract','OTHER','{LEARNING}',NULL),
('EFT','Electronic File Transfer (EFT)','OTHER','{LEARNING}',NULL),
('EXISTING_CMS_DATA_AND_PROCESS','Existing CMS data and process','OTHER','{LEARNING}',NULL),
('EDFR','Expanded Data Feedback Reporting (eDFR)','OTHER','{LEARNING}',NULL),
('GOVDELIVERY','GovDelivery','OTHER','{LEARNING}',NULL),
('GS','GrantSolutions','OTHER','{LEARNING}',NULL),
('HDR','Health Data Reporting (HDR)','OTHER','{LEARNING}',NULL),
('HPMS','Health Plan Management System (HPMS)','OTHER','{LEARNING}',NULL),
('HIGLAS','Healthcare Integrated General Ledger Accounting System (HIGLAS)','OTHER','{LEARNING}',NULL),
('IPC','Innovation Payment Contractor (IPC)','OTHER','{LEARNING}','IPC'),
('IDR','Integrated Data Repository (IDR)','OTHER','{LEARNING}',NULL),
('INTERNAL_STAFF','Internal staff','OTHER','{LEARNING}',NULL),
('LDG','Learning and Diffusion Group (LDG)','OTHER','{LEARNING}',NULL),
('LV','Legal Vertical (LV)','OTHER','{LEARNING}',NULL),
('MDM_POR','Master Data Management Program-Organization Relationship (MDM-POR)','OTHER','{LEARNING}','MDM'),
('MARX','Medicare Advantage Prescription Drug System (MARx)','OTHER','{LEARNING}',NULL),
('OTHER_NEW_PROCESS','Other new process','OTHER','{LEARNING}',NULL),
('OUTLOOK_MAILBOX','Outlook Mailbox','OTHER','{LEARNING}',NULL),
('QV','Quality Vertical (QV)','OTHER','{LEARNING}',NULL),
('RMADA','Research, Measurement, Assessment, Design, and Analysis (RMADA)','OTHER','{LEARNING}',NULL),
('ARS','Salesforce Application Review and Scoring (ARS)','OTHER','{LEARNING}',NULL),
('CONNECT','Salesforce CONNECT','OTHER','{LEARNING}',NULL),
('LOI','Salesforce Letter of Intent (LOI)','OTHER','{LEARNING}',NULL),
('POST_PORTAL','Salesforce Project Officer Support Tool or Portal (POST)','OTHER','{LEARNING}',NULL),
('RFA','Salesforce Request for Application (RFA)','OTHER','{LEARNING}',NULL),
('SHARED_SYSTEMS','Shared Systems','OTHER','{LEARNING}',NULL),
('BCDA','Beneficiary Claims Data API (BCDA)','OTHER','{LEARNING}',NULL),
('ISP','Innovation Support Platform','OTHER','{LEARNING}',NULL),
('MIDS','Measure and Instrument Development and Support (MIDS)','OTHER','{LEARNING}',NULL),
('MDM_NCBP','Master Data Management for Non-Claims-Based Payments (MDM-NCBP)','OTHER','{LEARNING}',NULL),
('MODEL_SPACE','Model Space','OTHER','{LEARNING}',NULL);
