-- UPDATE mto_solution 
-- SET mto_common_solution_key = NULL,
--     name = 'CMS QUALTRICS',
--     type = 'IT_SYSTEM',
--     poc_name = 'MINT Team',
--     poc_email = 'MINTTeam@cms.hhs.gov'
-- WHERE mto_common_solution_key = 'CMS_QUALTRICS'
