CREATE TYPE MTO_MILESTONE_RESPONSIBLE_COMPONENT AS ENUM (
    'CCIIO',
    'CCSQ',
    'CM',
    'CMCS',
    'CMMI_BSG',
    'CMMI_LDG',
    'CMMI_PCMG',
    'CMMI_PPG',
    'CMMI_RRCEG',
    'CMMI_SCMG',
    'CMMI_SPHG',
    'CPI',
    'FCHCO',
    'OA',
    'OACT',
    'OAGM',
    'OC',
    'OEDA',
    'OEOCR',
    'OFM',
    'OHC',
    'OHEI',
    'OHI',
    'OIT_AMG',
    'OIT_BOG',
    'OIT_EADG',
    'OIT_ESSG',
    'OIT_ICPG',
    'OIT_ISPG',
    'OIT_IUSG',
    'OIT_NTSS',
    'OL',
    'OMH',
    'OPOLE',
    'OSFLO',
    'OSORA',
    'OSPR'
);

ALTER TABLE mto_milestone
ADD COLUMN responsible_component MTO_MILESTONE_RESPONSIBLE_COMPONENT[] NOT NULL DEFAULT ARRAY[]::MTO_MILESTONE_RESPONSIBLE_COMPONENT[];
