-- Add new milestone keys to the MTO_COMMON_MILESTONE_KEY enum
-- Note: These must be in a separate migration from the INSERT statements
-- because PostgreSQL requires enum values to be committed before use

ALTER TYPE MTO_COMMON_MILESTONE_KEY ADD VALUE IF NOT EXISTS 'ACQUIRE_AN_IMP_CONT';
ALTER TYPE MTO_COMMON_MILESTONE_KEY ADD VALUE IF NOT EXISTS 'ACQUIRE_A_PRE_IMP_CONT';
ALTER TYPE MTO_COMMON_MILESTONE_KEY ADD VALUE IF NOT EXISTS 'ACQUIRE_A_DATA_AGG_CONT';
ALTER TYPE MTO_COMMON_MILESTONE_KEY ADD VALUE IF NOT EXISTS 'SEND_DASHBOARDS_REPORTS_TO_PART';
ALTER TYPE MTO_COMMON_MILESTONE_KEY ADD VALUE IF NOT EXISTS 'SEND_DATA_VIA_API_TO_PART';
ALTER TYPE MTO_COMMON_MILESTONE_KEY ADD VALUE IF NOT EXISTS 'SEND_RAW_FILES_TO_PART';
ALTER TYPE MTO_COMMON_MILESTONE_KEY ADD VALUE IF NOT EXISTS 'SIGN_COOPERATIVE_AGREEMENTS';
