ALTER TABLE mto_common_milestone
ADD COLUMN IF NOT EXISTS is_archived BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE mto_common_milestone
ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES user_account (id) NOT NULL DEFAULT '00000001-0001-0001-0001-000000000001';

ALTER TABLE mto_common_solution
ADD COLUMN IF NOT EXISTS created_dts TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();

ALTER TABLE mto_common_solution
ADD COLUMN IF NOT EXISTS modified_by UUID REFERENCES user_account (id) NOT NULL DEFAULT '00000001-0001-0001-0001-000000000001';

ALTER TABLE mto_common_solution
ADD COLUMN IF NOT EXISTS modified_dts TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
