-- CTAT enums and tables will be added to this migration as the implementation expands.
-- Future CTAT tables can pair these enum columns with *_other ZERO_STRING columns when OTHER is selected.

CREATE TYPE CTAT_CONTRACT_TYPE AS ENUM (
    'COST_PLUS_FIXED_FEE',
    'COST_REIMBURSEMENT',
    'FIRM_FIXED_PRICE',
    'INCENTIVE_CONTRACT',
    'TIME_AND_MATERIALS',
    'OTHER'
);

CREATE TYPE CTAT_CONTRACT_ACTIVITY_TYPE AS ENUM (
    'EVALUATION',
    'IMPLEMENTATION',
    'LEARNING',
    'TECHNICAL_ASSISTANCE',
    'OTHER'
);

CREATE TYPE CTAT_REQUEST_URGENCY AS ENUM (
    'HIGH',
    'MEDIUM',
    'LOW'
);

CREATE TYPE CTAT_BSG_DIVISION_OPTION AS ENUM (
    'DBOM',
    'DCCS',
    'DSSOS',
    'DTS',
    'OTHER'
);

CREATE TYPE CTAT_LDG_DIVISION_OPTION AS ENUM (
    'DMLS',
    'DAN',
    'OTHER'
);

CREATE TYPE CTAT_PCMG_DIVISION_OPTION AS ENUM (
    'DAPC',
    'DHCPM',
    'DSPM',
    'DAPM',
    'DPM',
    'OTHER'
);

CREATE TYPE CTAT_PPG_DIVISION_OPTION AS ENUM (
    'DAPMI',
    'DDA',
    'DESP',
    'DPMS',
    'OTHER'
);

CREATE TYPE CTAT_RREG_DIVISION_OPTION AS ENUM (
    'DHSR',
    'DPAR',
    'DSPR',
    'DRAM',
    'OTHER'
);

CREATE TYPE CTAT_SCMG_DIVISION_OPTION AS ENUM (
    'DHPI',
    'DFR',
    'DSI',
    'DDI',
    'OTHER'
);

CREATE TYPE CTAT_SPHG_DIVISION_OPTION AS ENUM (
    'DMPM',
    'DHII',
    'DPHII',
    'DHCD',
    'DSBI',
    'OTHER'
);

CREATE TYPE CTAT_HELP_NEEDED_TYPE AS ENUM (
    'CALM_SYSTEM_REQUISITION_SUPPORT',
    'CONTRACT_CHANGE_REQUEST_CCR_PROCESSING',
    'COR_TRANSCRIPT_REVIEW',
    'DEFINING_AND_DOCUMENTING_CONTRACT_REQUIREMENTS',
    'DELIVERABLE_EVALUATION_REVIEW_DER',
    'GUIDANCE_ON_DETERMINATIONS_AND_FINDINGS_DF',
    'GUIDANCE_ON_JUSTIFICATION_AND_APPROVAL_JA',
    'GUIDANCE_ON_MARKET_RESEARCH',
    'GUIDANCE_ON_TECHNICAL_EVALUATION_PANEL_TEP_MEMBERSHIP_SCORING_REPORTING',
    'INDEPENDENT_GOVERNMENT_COST_ESTIMATE_IGCE_PREPARATION',
    'POST_AWARD_ACTIONS_PAA',
    'REQUEST_FOR_CONTRACT_MEMO_RFC',
    'REQUEST_FOR_INFORMATION_RFI',
    'REQUEST_FOR_PROPOSAL_RFP',
    'REQUEST_FOR_QUOTATION_RFQ',
    'STATEMENT_OF_WORK_SOW_STATEMENT_OF_OBJECTIVES_SOO_PERFORMANCE_WORK_STATEMENT_PWS_DEVELOPMENT',
    'CONTRACTOR_PERFORMANCE_MANAGEMENT',
    'DATA_USE_AGREEMENT_DUA',
    'DELIVERABLE_EVALUATION_REVIEW_DER_MODIFICATION',
    'DOCUMENTING_AND_SUBMITTING_CONTRACTOR_PERFORMANCE_EVALUATIONS_CPARS',
    'ENTERPRISE_USER_ADMINISTRATION_EUA_JOB_CODES',
    'FOREIGN_NATIONAL_MANAGEMENT_SYSTEM_FNMS',
    'IDENTITY_AND_CREDENTIALING_TOOL_ICT',
    'INVOICE_PROCESSING_PLATFORM_IPP',
    'MAINTAINING_THE_ELECTRONIC_COR_ECOR_FILE',
    'POST_AWARD_ACTIONS_PAA_MODIFICATION',
    'OTHER'
);
