CREATE TYPE DISCUSSION_TOPIC_TYPE AS ENUM (
    'MODEL_PLAN_ALL',
    'MODEL_PLAN_MODEL_BASICS',
    'MODEL_PLAN_GENERAL_CHARACTERISTICS',
    'MODEL_PLAN_PARTICIPANTS_AND_PROVIDERS',
    'MODEL_PLAN_BENEFICIARIES',
    'MODEL_PLAN_OPERATIONS_EVALUATION_AND_LEARNING',
    'MODEL_PLAN_PAYMENT',
    'MODEL_TIMELINE',
    'DATA_EXCHANGE_APPROACH',
    'WAIVER_ASSESSMENT_SURVEY',
    '_4I_ACO_OS_QUESTIONNAIRE',
    'MODEL_TO_OPERATIONS_MATRIX_MTO',
    'DOCUMENTS',
    'CONTRACTS',
    'FFS_CRS_AND_TDLS',
    'OTHER'
);

ALTER TABLE plan_discussion ADD COLUMN IF NOT EXISTS topic DISCUSSION_TOPIC_TYPE NOT NULL DEFAULT 'OTHER';
