ALTER TYPE CTAT_HELP_NEEDED_TYPE RENAME VALUE 'CONTRACT_CHANGE_REQUEST_CCR_PROCESSING' TO 'CONTRACT_COST_REVIEW_CCR_PROCESSING';

ALTER TYPE CTAT_HELP_NEEDED_TYPE RENAME VALUE 'DELIVERABLE_EVALUATION_REVIEW_DER' TO 'DEPARTMENTAL_EFFICIENCY_REVIEW_DER';

ALTER TYPE CTAT_HELP_NEEDED_TYPE RENAME VALUE 'DELIVERABLE_EVALUATION_REVIEW_DER_MODIFICATION' TO 'DEPARTMENTAL_EFFICIENCY_REVIEW_DER_MODIFICATION';

ALTER TYPE CTAT_HELP_NEEDED_TYPE RENAME VALUE 'POST_AWARD_ACTIONS_PAA' TO 'POLITICAL_APPOINTEE_APPROVAL_PAA';

ALTER TYPE CTAT_HELP_NEEDED_TYPE RENAME VALUE 'POST_AWARD_ACTIONS_PAA_MODIFICATION' TO 'POLITICAL_APPOINTEE_APPROVAL_PAA_MODIFICATION';
