-- INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(1, 'Other', 'OTHER', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(1, 'Manage Part C/D enrollment', 'MANAGE_CD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(2, 'Review and collect plan bids', 'REV_COL_BIDS', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(3, 'Update the plan’s contract', 'UPDATE_CONTRACT', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(4, 'Advertise the model', 'ADVERTISE_MODEL', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(5, 'Collect, review, and score applications', 'COL_REV_SCORE_APP', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(6, 'Obtain an application support contractor', 'APP_SUPPORT_CON', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(7, 'Communicate with participants', 'COMM_W_PART', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(8, 'Manage provider overlaps', 'MANAGE_PROV_OVERLAP', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(9, 'Manage beneficiary overlaps', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(10, 'Helpdesk support', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(11, 'IDDOC support', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(12, 'Establish a benchmark with participants', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(13, 'Process participant appeals', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(14, 'Acquire an evaluation contractor', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(15, 'Data to monitor the model', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(16, 'Data to support model evaluation', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(17, 'Claims-based measures', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(18, 'Quality performance scores', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(19, 'Send reports/data to participants', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(20, 'Acquire a learning contractor', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(21, 'Participant-to-participant collaboration', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(22, 'Educate beneficiaries', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(23, 'Adjust how FFS claims are paid', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(24, 'Manage FFS excluded payments', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(25, 'Make non-claims based payments', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(26, 'Compute shared savings payment', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(27, 'Recover payments', 'TBD', 'MINT');
