INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(1, 'Other', 'OTHER', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(2, 'Medicare Advantage Prescription Drug System (MARx)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(3, 'Health Plan Management System (HPMS)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(4, 'Salesforce', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(5, 'Grant Solutions', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(6, 'Salesforce Request for Application (RFA)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(7, 'Salesforce Application Review and Scoring (ARS)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(8, 'Research, Measurement, Assessment, Design, and Analysis (RMADA)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(9, 'Outlook Mailbox', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(10, 'GovDelivery', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(11, 'Salesforce Portal', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(12, 'Master Data Management (MDM)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(13, 'Consolidated Business Operations Support Center (CBOSC)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(14, 'Through a contractor', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(15, 'Accountable Care Organization Operating System (ACO-OS)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(16, 'Accountable Care Organization User Interface (ACO UI)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(17, '4innovation (4i)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(18, 'Integrated Data Repository (IDR)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(19, 'Chronic Conditions Warehouse (CCW)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(20, 'Medicare Appeal System', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(21, 'Innovation Development and Operation Services (IDOS)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(22, 'Innovation Support Platform (ISP)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(23, 'Another contractor', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(24, 'Existing CMS data and process', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(25, 'Health Data Reporting (new CMMI process)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(26, 'Other new process', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(27, 'Internal staff', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(28, 'A cross-model contract', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(29, 'Connect (a Salesforce tool)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(30, 'Office of Communications (OC)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(31, 'Shared Systems', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(32, 'Healthcare Integrated General Ledger Accounting System (HIGLAS)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(33, 'FFS Competency Center', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(34, 'Automated Plan Payment System (APPS)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(35, 'Innovation Payment Contractor (IPC)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(36, 'Medicare Administrative Contractor (MAC)', 'TBD', 'MINT');
INSERT INTO "public"."possible_operational_need"("id", "full_name", "short_name", "created_by") VALUES(37, 'Research, Measurement, Assessment, Design, and Analysis (RMADA) contractor', 'TBD', 'MINT');
