INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(1, 'Medicare Advantage Prescription Drug System (MARx)', 'MARX', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(2, 'Health Plan Management System (HPMS)', 'HPMS', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(3, 'Salesforce', 'SALESFORCE', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(4, 'Grant Solutions', 'GRANT_SOLUTIONS', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(5, 'Salesforce Request for Application (RFA)', 'RFA', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(6, 'Salesforce Application Review and Scoring (ARS)', 'ARS', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(7, 'Research, Measurement, Assessment, Design, and Analysis (RMADA)', 'RMADA', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(8, 'Outlook Mailbox', 'OUTLOOK_MAILBOX', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(9, 'GovDelivery', 'GOVDELIVERY', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(10, 'Salesforce Portal', 'SALESFORCE_PORTAL', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(11, 'Master Data Management (MDM)', 'MDM', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(12, 'Consolidated Business Operations Support Center (CBOSC)', 'CBOSC', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(13, 'Through a contractor', 'THROUGH_A_CONTRACTOR', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(14, 'Accountable Care Organization Operating System (ACO-OS)', 'ACO_OS', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(15, 'Accountable Care Organization User Interface (ACO UI)', 'ACO_UI', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(16, '4innovation (4i)', 'INNOVATION', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(17, 'Integrated Data Repository (IDR)', 'IDR', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(18, 'Chronic Conditions Warehouse (CCW)', 'CCW', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(19, 'Medicare Appeal System', 'MEDICARE_APPEAL_SYSTEM', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(20, 'Innovation Development and Operation Services (IDOS)', 'IDOS', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(21, 'Innovation Support Platform (ISP)', 'ISP', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(22, 'Another contractor', 'ANOTHER_CONTRACTOR', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(23, 'Existing CMS data and process', 'EXISTING_CMS_DATA_AND_PROCESS', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(24, 'Health Data Reporting (new CMMI process)', 'NEW_CMMI_PROCESS', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(25, 'Other new process', 'OTHER_NEW_PROCESS', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(26, 'Internal staff', 'INTERNAL_STAFF', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(27, 'A cross-model contract', 'CROSS_MODEL_CONTRACT', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(28, 'Connect (a Salesforce tool)', 'CONNECT', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(29, 'Office of Communications (OC)', 'OC', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(30, 'Shared Systems', 'SHARED_SYSTEMS', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(31, 'Healthcare Integrated General Ledger Accounting System (HIGLAS)', 'HIGLAS', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(32, 'FFS Competency Center', 'FFS_COMPETENCY_CENTER', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(33, 'Automated Plan Payment System (APPS)', 'APPS', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(34, 'Innovation Payment Contractor (IPC)', 'IPC', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(35, 'Medicare Administrative Contractor (MAC)', 'MAC', 'MINT');
INSERT INTO "public"."possible_operational_solution"("id", "sol_name", "sol_key", "created_by") VALUES(36, 'Research, Measurement, Assessment, Design, and Analysis (RMADA) contractor', 'RMADA_CONTRACTOR', 'MINT');
