CREATE TYPE model_category AS ENUM (
    'ACCOUNTABLE_CARE',
    'DEMONSTRATION',
    'EPISODE_BASED_PAYMENT_INITIATIVES',
    'INIT_MEDICAID_CHIP_POP',
    'INIT__MEDICARE_MEDICAID_ENROLLEES',
    'INIT_ACCEL_DEV_AND_TEST',
    'INIT_SPEED_ADOPT_BEST_PRACTICE',
    'PRIMARY_CARE_TRANSFORMATION',
    'UNKNOWN'
);
CREATE TYPE model_plan_status AS ENUM (
    'PLAN_DRAFT',
    'PLAN_COMPLETE',
    'ICIP_COMPLETE',
    'INTERNAL_CMMI_CLEARANCE',
    'CMS_CLEARANCE',
    'HHS_CLEARANCE',
    'OMB_ASRF_CLEARANCE',
    'CLEARED',
    'ANNOUNCED'
);
CREATE TYPE cms_center AS ENUM (
    'CMMI',
    'CENTER_FOR_MEDICARE',
    'FEDERAL_COORDINATED_HEALTH_CARE_OFFICE',
    'CENTER_FOR_CLINICAL_STANDARDS_AND_QUALITY',
    'CENTER_FOR_PROGRAM_INTEGRITY',
    'OTHER'
);
CREATE TYPE cmmi_group AS ENUM (
    'PATIENT_CARE_MODELS_GROUP',
    'POLICY_AND_PROGRAMS_GROUP',
    'PREVENTIVE_AND_POPULATION_HEALTH_CARE_MODELS_GROUP',
    'SEAMLESS_CARE_MODELS_GROUP',
    'STATE_INNOVATIONS_GROUP',
    'TBD'
);
CREATE TYPE team_role AS ENUM (
    'MODEL_LEAD',
    'MODEL_TEAM',
    'LEADERSHIP',
    'LEARNING',
    'EVALUATION'
);
CREATE TYPE model_type AS ENUM ('VOLUNTARY', 'MANDATORY', 'TBD');
CREATE TYPE tri_state_answer AS ENUM ('YES', 'NO', 'TBD');


CREATE TYPE task_status AS ENUM ('READY', 'IN_PROGRESS', 'COMPLETE')
