CREATE TYPE MODEL_CATEGORY AS ENUM (
    'ACCOUNTABLE_CARE',
    'DEMONSTRATION',
    'EPISODE_BASED_PAYMENT_INITIATIVES',
    'INIT_MEDICAID_CHIP_POP',
    'INIT__MEDICARE_MEDICAID_ENROLLEES',
    'INIT_ACCEL_DEV_AND_TEST',
    'INIT_SPEED_ADOPT_BEST_PRACTICE',
    'PRIMARY_CARE_TRANSFORMATION',
    'UNKNOWN'
);
CREATE TYPE MODEL_PLAN_STATUS AS ENUM (
    'PLAN_DRAFT',
    'PLAN_COMPLETE',
    'ICIP_COMPLETE',
    'INTERNAL_CMMI_CLEARANCE',
    'CMS_CLEARANCE',
    'HHS_CLEARANCE',
    'OMB_ASRF_CLEARANCE',
    'CLEARED',
    'ANNOUNCED'
);
CREATE TYPE CMS_CENTER AS ENUM (
    'CMMI',
    'CENTER_FOR_MEDICARE',
    'FEDERAL_COORDINATED_HEALTH_CARE_OFFICE',
    'CENTER_FOR_CLINICAL_STANDARDS_AND_QUALITY',
    'CENTER_FOR_PROGRAM_INTEGRITY',
    'OTHER'
);
CREATE TYPE CMMI_GROUP AS ENUM (
    'PATIENT_CARE_MODELS_GROUP',
    'POLICY_AND_PROGRAMS_GROUP',
    'PREVENTIVE_AND_POPULATION_HEALTH_CARE_MODELS_GROUP',
    'SEAMLESS_CARE_MODELS_GROUP',
    'STATE_INNOVATIONS_GROUP',
    'TBD'
);
CREATE TYPE TEAM_ROLE AS ENUM (
    'MODEL_LEAD',
    'MODEL_TEAM',
    'LEADERSHIP',
    'LEARNING',
    'EVALUATION'
);
CREATE TYPE MODEL_TYPE AS ENUM ('VOLUNTARY', 'MANDATORY', 'TBD');
CREATE TYPE TRI_STATE_ANSWER AS ENUM ('YES', 'NO', 'TBD');



CREATE TYPE DOCUMENT_TYPE AS ENUM ('CONCEPT_PAPER', 'POLICY_PAPER', 'ICIP_DRAFT', 'MARKET_RESEARCH', 'OTHER');

CREATE TYPE DISCUSSION_STATUS AS ENUM ('ANSWERED', 'WAITING_FOR_RESPONSE', 'UNANSWERED');

CREATE TYPE TASK_STATUS AS ENUM ('READY', 'IN_PROGRESS', 'COMPLETE');


CREATE TYPE CONFIDENCE_TYPE AS ENUM (
    'NOT_AT_ALL',
    'SLIGHTLY',
    'FAIRLY',
    'COMPLETELY'
);

CREATE TYPE FREQUENCY_TYPE AS ENUM (
    'ANNUALLY',
    'BIANNUALLY',
    'QUARTERLY',
    'MONTHLY',
    'ROLLING',
    'OTHER'
);
