CREATE TYPE TEAM_ROLE AS ENUM (
    'MODEL_LEAD',
    'MODEL_TEAM',
    'LEADERSHIP',
    'LEARNING',
    'EVALUATION'
);
CREATE TYPE MODEL_TYPE AS ENUM ('VOLUNTARY', 'MANDATORY', 'TBD');

CREATE TYPE TRI_STATE_ANSWER AS ENUM ('YES', 'NO', 'TBD');

CREATE TYPE DOCUMENT_TYPE AS ENUM ('CONCEPT_PAPER', 'POLICY_PAPER', 'ICIP_DRAFT', 'MARKET_RESEARCH', 'OTHER');

CREATE TYPE DISCUSSION_STATUS AS ENUM ('ANSWERED', 'WAITING_FOR_RESPONSE', 'UNANSWERED');

CREATE TYPE TASK_STATUS AS ENUM ('READY', 'IN_PROGRESS', 'COMPLETE');


CREATE TYPE CONFIDENCE_TYPE AS ENUM (
    'NOT_AT_ALL',
    'SLIGHTLY',
    'FAIRLY',
    'COMPLETELY'
);

CREATE TYPE FREQUENCY_TYPE AS ENUM (
    'ANNUALLY',
    'BIANNUALLY',
    'QUARTERLY',
    'MONTHLY',
    'ROLLING',
    'OTHER'
);

CREATE TYPE OVERLAP_TYPE AS ENUM (
    'YES_NEED_POLICIES',
    'YES_NO_ISSUES',
    'NO'

);
