ALTER TYPE action_type ADD VALUE 'BIZ_CASE_NEEDS_CHANGES';
ALTER TYPE action_type ADD VALUE 'PROVIDE_GRT_FEEDBACK_BIZ_CASE_FINAL';
ALTER TYPE action_type ADD VALUE 'PROVIDE_GRT_FEEDBACK_BIZ_CASE_DRAFT';
ALTER TYPE action_type ADD VALUE 'NO_GOVERNANCE_NEEDED';
