CREATE TYPE CMS_CENTER AS ENUM (
    'CMMI',
    'CENTER_FOR_MEDICARE',
    'FEDERAL_COORDINATED_HEALTH_CARE_OFFICE',
    'CENTER_FOR_CLINICAL_STANDARDS_AND_QUALITY',
    'CENTER_FOR_PROGRAM_INTEGRITY',
    'OTHER'
);
CREATE TYPE CMMI_GROUP AS ENUM (
    'PATIENT_CARE_MODELS_GROUP',
    'POLICY_AND_PROGRAMS_GROUP',
    'PREVENTIVE_AND_POPULATION_HEALTH_CARE_MODELS_GROUP',
    'SEAMLESS_CARE_MODELS_GROUP',
    'STATE_INNOVATIONS_GROUP',
    'TBD'
);
CREATE TABLE model_plan (
    id UUID PRIMARY KEY NOT NULL,
    model_name ZERO_STRING NOT NULL,
    model_category MODEL_CATEGORY, --select from list
    cms_centers CMS_CENTER[], --should select from list
    cms_other ZERO_STRING,
    cmmi_groups CMMI_GROUP[],
    archived BOOL NOT NULL DEFAULT FALSE,
    status MODEL_PLAN_STATUS NOT NULL,
    created_by EUA_ID NOT NULL,
    created_dts TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by EUA_ID,
    modified_dts TIMESTAMP WITH TIME ZONE
);
