CREATE TYPE MODEL_PLAN_STATUS AS ENUM (
    'PLAN_DRAFT',
    'PLAN_COMPLETE',
    'ICIP_COMPLETE',
    'INTERNAL_CMMI_CLEARANCE',
    'CMS_CLEARANCE',
    'HHS_CLEARANCE',
    'OMB_ASRF_CLEARANCE',
    'CLEARED',
    'ANNOUNCED'
);

CREATE TABLE model_plan (
    id UUID PRIMARY KEY NOT NULL,
    model_name ZERO_STRING NOT NULL,
    archived BOOL NOT NULL DEFAULT FALSE,
    status MODEL_PLAN_STATUS NOT NULL,
    created_by EUA_ID NOT NULL,
    created_dts TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by EUA_ID,
    modified_dts TIMESTAMP WITH TIME ZONE
);
