/* Delete all IT_Tools entries*/
DELETE FROM PLAN_IT_TOOLS;

/* Drop Table */
DROP TABLE PLAN_IT_TOOLS;

/* Drop referenced Types that aren't used anywhere else */
DROP TYPE GC_PART_C_D_TYPE, GC_COLLECT_BIDS_TYPE, GC_UPDATE_CONTRACT_TYPE, PP_TO_ADVERTISE_TYPE, PP_COLLECT_SCORE_REVIEW_TYPE, PP_APP_SUPPORT_CONTRACTOR_TYPE, PP_COMMUNICATE_WITH_PARTICIPANT_TYPE, PP_MANAGE_PROVIDER_OVERLAP_TYPE, B_MANAGE_BENEFICIARY_OVERLAP_TYPE, OEL_HELPDESK_SUPPORT_TYPE, OEL_MANAGE_ACO_TYPE, OEL_PERFORMANCE_BENCHMARK_TYPE, OEL_PROCESS_APPEALS_TYPE, OEL_EVALUATION_CONTRACTOR_TYPE, OEL_COLLECT_DATA_TYPE, OEL_OBTAIN_DATA_TYPE, OEL_CLAIMS_BASED_MEASURES_TYPE, OEL_QUALITY_SCORES_TYPE, OEL_SEND_REPORTS_TYPE, OEL_LEARNING_CONTRACTOR_TYPE, OEL_PARTICIPANT_COLLABORATION_TYPE, OEL_EDUCATE_BENEFICIARIES_TYPE, P_MAKE_CLAIMS_PAYMENTS_TYPE, P_INFORM_FFS_TYPE, P_NON_CLAIMS_BASED_PAYMENTS_TYPE, P_SHARED_SAVINGS_PLAN_TYPE, P_RECOVER_PAYMENTS_TYPE;


/*Remove enum entry for IT tools */

/* You can't drop enum values in GQL. This renames the old type, creates a new type, then updated the data type to the new type */
ALTER TYPE TASK_LIST_SECTION RENAME TO TASK_LIST_SECTION_OLD;

CREATE TYPE TASK_LIST_SECTION AS ENUM (
    'BASICS',
    'GENERAL_CHARACTERISTICS',
    'PARTICIPANTS_AND_PROVIDERS',
    'BENEFICIARIES',
    'OPERATIONS_EVALUATION_AND_LEARNING',
    'PAYMENT',
    'PREPARE_FOR_CLEARANCE'
);

/* Set column to text */
ALTER TABLE possible_operational_need
ALTER COLUMN section TYPE TEXT;

/* Drop old type */

DROP TYPE TASK_LIST_SECTION_OLD;

/* Update the type on the column to be the new type, and provide a casting mechanism to convert to the new type */
ALTER TABLE possible_operational_need
ALTER COLUMN section TYPE TASK_LIST_SECTION
USING (section::TASK_LIST_SECTION);
