/* Create the Function */
CREATE FUNCTION CREATE_POSSIBLE_NEED_SOLUTION_LINK(possibleNeedKey OPERATIONAL_NEED_KEY, possibleSolutionKeys OPERATIONAL_SOLUTION_KEY[]) RETURNS VOID AS $body$
BEGIN
WITH OPSolKey AS
(
	SELECT
	unnest(possibleSolutionKeys) AS SolKey
	,possibleNeedKey AS NeedKey
),
ENTRIES AS 
(
SELECT OPSolKey.SolKey, pos.id as SolID, OPSolKey.NeedKey, pon.id as NeedID FROM OPSolKey 
	JOIN possible_operational_solution AS pos on pos.sol_key = OPSolKey.SolKey
	JOIN possible_operational_need AS pon on pon.need_key = OPSolKey.NeedKey
)
INSERT INTO possible_need_solution_link (
        need_type,
        solution_type,
        created_by
)
SELECT NeedID,SolID,'00000001-0001-0001-0001-000000000001' FROM ENTRIES; --System Account

END
$body$ LANGUAGE plpgsql;

/* Update the Links */

/* TODO: get the rest of the links working */
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('MANAGE_CD'::OPERATIONAL_NEED_KEY, '{MARX}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('REV_COL_BIDS'::OPERATIONAL_NEED_KEY, '{HPMS}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('UPDATE_CONTRACT'::OPERATIONAL_NEED_KEY, '{HPMS}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('RECRUIT_PARTICIPANTS'::OPERATIONAL_NEED_KEY, '{GS, CMS_QUALTRICS, LOI, RFA}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('REV_SCORE_APP'::OPERATIONAL_NEED_KEY, '{GS, ARS}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('APP_SUPPORT_CON'::OPERATIONAL_NEED_KEY, '{RMADA}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('COMM_W_PART'::OPERATIONAL_NEED_KEY, '{GOVDELIVERY, OUTLOOK_MAILBOX, POST_PORTAL}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('MANAGE_PROV_OVERLAP'::OPERATIONAL_NEED_KEY, '{MDM}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('MANAGE_BEN_OVERLAP'::OPERATIONAL_NEED_KEY, '{MDM}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('HELPDESK_SUPPORT'::OPERATIONAL_NEED_KEY, '{CBOSC, CONTRACTOR}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('IDDOC_SUPPORT'::OPERATIONAL_NEED_KEY, '{INNOVATION, ACO_OS}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('ESTABLISH_BENCH'::OPERATIONAL_NEED_KEY, '{IDR, CCW}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('PROCESS_PART_APPEALS'::OPERATIONAL_NEED_KEY, '{LV}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('ACQUIRE_AN_EVAL_CONT'::OPERATIONAL_NEED_KEY, '{RMADA}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('DATA_TO_MONITOR'::OPERATIONAL_NEED_KEY, '{CDX, CCW, CONTRACTOR, HDR, IDR, POST_PORTAL}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('DATA_TO_SUPPORT_EVAL'::OPERATIONAL_NEED_KEY, '{CDX, CCW, HDR, POST_PORTAL}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('CLAIMS_BASED_MEASURES'::OPERATIONAL_NEED_KEY, '{CCW, IDR}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('QUALITY_PERFORMANCE_SCORES'::OPERATIONAL_NEED_KEY, '{EXISTING_CMS_DATA_AND_PROCESS, HDR, OTHER_NEW_PROCESS}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('SEND_REPDATA_TO_PART'::OPERATIONAL_NEED_KEY, '{INNOVATION, CDX, CMS_BOX, EFT, EDFR, INTERNAL_STAFF, RMADA, POST_PORTAL}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('ACQUIRE_A_LEARN_CONT'::OPERATIONAL_NEED_KEY, '{CROSS_MODEL_CONTRACT, RMADA}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('PART_TO_PART_COLLAB'::OPERATIONAL_NEED_KEY, '{CONNECT}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('EDUCATE_BENEF'::OPERATIONAL_NEED_KEY, '{LDG}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('ADJUST_FFS_CLAIMS'::OPERATIONAL_NEED_KEY, '{HIGLAS, SHARED_SYSTEMS}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('MANAGE_FFS_EXCL_PAYMENTS'::OPERATIONAL_NEED_KEY, '{SHARED_SYSTEMS}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('MAKE_NON_CLAIMS_BASED_PAYMENTS'::OPERATIONAL_NEED_KEY, '{APPS, HIGLAS, IPC}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('COMPUTE_SHARED_SAVINGS_PAYMENT'::OPERATIONAL_NEED_KEY, '{RMADA}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('RECOVER_PAYMENTS'::OPERATIONAL_NEED_KEY, '{APPS, IPC, SHARED_SYSTEMS}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('SIGN_PARTICIPATION_AGREEMENTS'::OPERATIONAL_NEED_KEY, '{INNOVATION, CONTRACTOR}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('VET_PROVIDERS_FOR_PROGRAM_INTEGRITY'::OPERATIONAL_NEED_KEY, '{CPI_VETTING}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('UTILIZE_QUALITY_MEASURES_DEVELOPMENT_CONTRACTOR'::OPERATIONAL_NEED_KEY, '{QV}'::OPERATIONAL_SOLUTION_KEY[]);
SELECT CREATE_POSSIBLE_NEED_SOLUTION_LINK('IT_PLATFORM_FOR_LEARNING'::OPERATIONAL_NEED_KEY, '{CONNECT}'::OPERATIONAL_SOLUTION_KEY[]);
