[[cron]]
  schedule = "*/5 * * * *"
  [cron.job]
    type = "DailyDigestCronJob"
    queue = "critical"
[[cron]]
  schedule = "*/2 * * * *"
  [cron.job]
    type = "TranslateAuditCronJob"
    queue = "critical"