// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/shared/pubsub/pubsub.go

// Package mockpubsub is a generated GoMock package.
package mockpubsub

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"

	pubsub "github.com/cmsgov/mint-app/pkg/shared/pubsub"
)

// MockPubSub is a mock of PubSub interface.
type MockPubSub struct {
	ctrl     *gomock.Controller
	recorder *MockPubSubMockRecorder
}

// MockPubSubMockRecorder is the mock recorder for MockPubSub.
type MockPubSubMockRecorder struct {
	mock *MockPubSub
}

// NewMockPubSub creates a new mock instance.
func NewMockPubSub(ctrl *gomock.Controller) *MockPubSub {
	mock := &MockPubSub{ctrl: ctrl}
	mock.recorder = &MockPubSubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPubSub) EXPECT() *MockPubSubMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPubSub) Publish(sessionID uuid.UUID, eventType pubsub.EventType, payload interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", sessionID, eventType, payload)
}

// Publish indicates an expected call of Publish.
func (mr *MockPubSubMockRecorder) Publish(sessionID, eventType, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPubSub)(nil).Publish), sessionID, eventType, payload)
}

// Subscribe mocks base method.
func (m *MockPubSub) Subscribe(sessionID uuid.UUID, eventType pubsub.EventType, subscriber pubsub.Subscriber, onDisconnect <-chan struct{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", sessionID, eventType, subscriber, onDisconnect)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockPubSubMockRecorder) Subscribe(sessionID, eventType, subscriber, onDisconnect interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockPubSub)(nil).Subscribe), sessionID, eventType, subscriber, onDisconnect)
}

// Unsubscribe mocks base method.
func (m *MockPubSub) Unsubscribe(sessionID uuid.UUID, eventType pubsub.EventType, subscriberID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", sessionID, eventType, subscriberID)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockPubSubMockRecorder) Unsubscribe(sessionID, eventType, subscriberID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockPubSub)(nil).Unsubscribe), sessionID, eventType, subscriberID)
}
