export const BASIC_NONPROD = 'MINT_USER_NONPROD';
export const BASIC = 'MINT_USER';
export const ASSESSMENT_NONPROD = 'MINT_ASSESSMENT_NONPROD';
export const ASSESSMENT = 'MINT_ASSESSMENT';
export const MAC = 'MINT MAC Users';

export const NONPROD_JOB_CODES = [BASIC_NONPROD, ASSESSMENT_NONPROD, MAC];

export const JOB_CODES = [
  BASIC,
  ASSESSMENT,
  BASIC_NONPROD,
  ASSESSMENT_NONPROD,
  MAC
];

export default JOB_CODES;
