INSERT INTO existing_model_link(
    id,
    model_plan_id,
    existing_model_id,
    current_model_plan_id,
    created_by,
    created_dts,
    modified_by,
    modified_dts
)
VALUES(
    :id,
    :model_plan_id,
    :existing_model_id,
    :current_model_plan_id,
    :created_by,
    :created_dts,
    :modified_by,
    :modified_dts
)
RETURNING
id,
model_plan_id,
existing_model_id,
current_model_plan_id,
created_by,
created_dts,
modified_by,
modified_dts;
