// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/graph/resolvers/plan_task_list_section_locks.go

// Package mockresolvers is a generated GoMock package.
package mockresolvers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"

	model "github.com/cmsgov/mint-app/pkg/graph/model"
	pubsub "github.com/cmsgov/mint-app/pkg/shared/pubsub"
)

// MockPlanTaskListSectionLocks is a mock of PlanTaskListSectionLocks interface.
type MockPlanTaskListSectionLocks struct {
	ctrl     *gomock.Controller
	recorder *MockPlanTaskListSectionLocksMockRecorder
}

// MockPlanTaskListSectionLocksMockRecorder is the mock recorder for MockPlanTaskListSectionLocks.
type MockPlanTaskListSectionLocksMockRecorder struct {
	mock *MockPlanTaskListSectionLocks
}

// NewMockPlanTaskListSectionLocks creates a new mock instance.
func NewMockPlanTaskListSectionLocks(ctrl *gomock.Controller) *MockPlanTaskListSectionLocks {
	mock := &MockPlanTaskListSectionLocks{ctrl: ctrl}
	mock.recorder = &MockPlanTaskListSectionLocksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanTaskListSectionLocks) EXPECT() *MockPlanTaskListSectionLocksMockRecorder {
	return m.recorder
}

// GetTaskListSectionLocks mocks base method.
func (m *MockPlanTaskListSectionLocks) GetTaskListSectionLocks(modelPlanID uuid.UUID) ([]*model.TaskListSectionLockStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskListSectionLocks", modelPlanID)
	ret0, _ := ret[0].([]*model.TaskListSectionLockStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskListSectionLocks indicates an expected call of GetTaskListSectionLocks.
func (mr *MockPlanTaskListSectionLocksMockRecorder) GetTaskListSectionLocks(modelPlanID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskListSectionLocks", reflect.TypeOf((*MockPlanTaskListSectionLocks)(nil).GetTaskListSectionLocks), modelPlanID)
}

// LockTaskListSection mocks base method.
func (m *MockPlanTaskListSectionLocks) LockTaskListSection(ps pubsub.PubSub, modelPlanID uuid.UUID, section, principal string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockTaskListSection", ps, modelPlanID, section, principal)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockTaskListSection indicates an expected call of LockTaskListSection.
func (mr *MockPlanTaskListSectionLocksMockRecorder) LockTaskListSection(ps, modelPlanID, section, principal interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockTaskListSection", reflect.TypeOf((*MockPlanTaskListSectionLocks)(nil).LockTaskListSection), ps, modelPlanID, section, principal)
}

// SubscribeTaskListSectionLockChanges mocks base method.
func (m *MockPlanTaskListSectionLocks) SubscribeTaskListSectionLockChanges(ps pubsub.PubSub, modelPlanID uuid.UUID, principal string, onDisconnect <-chan struct{}) (<-chan *model.TaskListSectionLockStatusChanged, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeTaskListSectionLockChanges", ps, modelPlanID, principal, onDisconnect)
	ret0, _ := ret[0].(<-chan *model.TaskListSectionLockStatusChanged)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeTaskListSectionLockChanges indicates an expected call of SubscribeTaskListSectionLockChanges.
func (mr *MockPlanTaskListSectionLocksMockRecorder) SubscribeTaskListSectionLockChanges(ps, modelPlanID, principal, onDisconnect interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeTaskListSectionLockChanges", reflect.TypeOf((*MockPlanTaskListSectionLocks)(nil).SubscribeTaskListSectionLockChanges), ps, modelPlanID, principal, onDisconnect)
}

// UnlockAllTaskListSections mocks base method.
func (m *MockPlanTaskListSectionLocks) UnlockAllTaskListSections(ps pubsub.PubSub, modelPlanID uuid.UUID) []model.TaskListSectionLockStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockAllTaskListSections", ps, modelPlanID)
	ret0, _ := ret[0].([]model.TaskListSectionLockStatus)
	return ret0
}

// UnlockAllTaskListSections indicates an expected call of UnlockAllTaskListSections.
func (mr *MockPlanTaskListSectionLocksMockRecorder) UnlockAllTaskListSections(ps, modelPlanID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockAllTaskListSections", reflect.TypeOf((*MockPlanTaskListSectionLocks)(nil).UnlockAllTaskListSections), ps, modelPlanID)
}

// UnlockTaskListSection mocks base method.
func (m *MockPlanTaskListSectionLocks) UnlockTaskListSection(ps pubsub.PubSub, modelPlanID uuid.UUID, section, principal string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockTaskListSection", ps, modelPlanID, section, principal)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlockTaskListSection indicates an expected call of UnlockTaskListSection.
func (mr *MockPlanTaskListSectionLocksMockRecorder) UnlockTaskListSection(ps, modelPlanID, section, principal interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockTaskListSection", reflect.TypeOf((*MockPlanTaskListSectionLocks)(nil).UnlockTaskListSection), ps, modelPlanID, section, principal)
}
