package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/graph/model"
)

// CtatRequest is the resolver for the ctatRequest field.
func (r *queryResolver) CtatRequest(ctx context.Context, id uuid.UUID) (*model.CTATRequest, error) {
	panic(fmt.Errorf("not implemented: CtatRequest - ctatRequest"))
}

// CtatRequests is the resolver for the ctatRequests field.
func (r *queryResolver) CtatRequests(ctx context.Context) ([]*model.CTATRequest, error) {
	panic(fmt.Errorf("not implemented: CtatRequests - ctatRequests"))
}
