package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/graph/model"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// TypeOfHelpNeeded is the resolver for the typeOfHelpNeeded field.
func (r *cTATRequestResolver) TypeOfHelpNeeded(ctx context.Context, obj *models.CTATRequest) ([]models.CTATHelpNeededType, error) {
	return obj.TypeOfHelpNeeded, nil
}

// CreateCTATRequest is the resolver for the createCTATRequest field.
func (r *mutationResolver) CreateCTATRequest(ctx context.Context, input model.CTATRequestInput) (*models.CTATRequest, error) {
	panic(fmt.Errorf("not implemented: CreateCTATRequest - createCTATRequest"))
}

// AdminUpdateCTATRequest is the resolver for the adminUpdateCTATRequest field.
func (r *mutationResolver) AdminUpdateCTATRequest(ctx context.Context, input model.CTATAdminUpdateInput) (*models.CTATRequest, error) {
	panic(fmt.Errorf("not implemented: AdminUpdateCTATRequest - adminUpdateCTATRequest"))
}

// CtatRequest is the resolver for the ctatRequest field.
func (r *queryResolver) CtatRequest(ctx context.Context, id uuid.UUID) (*models.CTATRequest, error) {
	panic(fmt.Errorf("not implemented: CtatRequest - ctatRequest"))
}

// CtatRequests is the resolver for the ctatRequests field.
func (r *queryResolver) CtatRequests(ctx context.Context) ([]*models.CTATRequest, error) {
	panic(fmt.Errorf("not implemented: CtatRequests - ctatRequests"))
}

// CTATRequest returns generated.CTATRequestResolver implementation.
func (r *Resolver) CTATRequest() generated.CTATRequestResolver { return &cTATRequestResolver{r} }

type cTATRequestResolver struct{ *Resolver }
