package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/graph/model"
)

// CustomTimelineDate is the resolver for the customTimelineDate field.
func (r *queryResolver) CustomTimelineDate(ctx context.Context, id uuid.UUID) (*model.CustomTimelineDate, error) {
	panic(fmt.Errorf("not implemented: CustomTimelineDate - customTimelineDate"))
}
