package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/appcontext"
	"github.com/cms-enterprise/mint-app/pkg/graph/model"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// CreateCustomTimelineDate is the resolver for the createCustomTimelineDate field.
func (r *mutationResolver) CreateCustomTimelineDate(ctx context.Context, input model.CustomTimelineDateCreateInput) (*models.CustomTimelineDate, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)

	return CustomTimelineDateCreate(
		ctx,
		logger,
		&input,
		principal,
		r.store,
		r.emailService,
		r.addressBook,
	)
}

// UpdateCustomTimelineDate is the resolver for the updateCustomTimelineDate field.
func (r *mutationResolver) UpdateCustomTimelineDate(ctx context.Context, id uuid.UUID, changes map[string]any) (*models.CustomTimelineDate, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)

	return CustomTimelineDateUpdate(ctx, logger, id, changes, principal, r.store)
}

// DeleteCustomTimelineDate is the resolver for the deleteCustomTimelineDate field.
func (r *mutationResolver) DeleteCustomTimelineDate(ctx context.Context, id uuid.UUID) (*models.CustomTimelineDate, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)

	return DeleteCustomTimelineDate(ctx, logger, principal, r.store, id)
}

// CustomTimelineDate is the resolver for the customTimelineDate field.
func (r *queryResolver) CustomTimelineDate(ctx context.Context, id uuid.UUID) (*models.CustomTimelineDate, error) {
	return CustomTimelineDateGetByIDLOADER(ctx, id)
}
