package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/graph/model"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// TechnicalContactsIdentifiedDetail is the resolver for the technicalContactsIdentifiedDetail field.
func (r *iDDOCQuestionnaireResolver) TechnicalContactsIdentifiedDetail(ctx context.Context, obj *models.IDDOCQuestionnaire) (*string, error) {
	panic(fmt.Errorf("not implemented: TechnicalContactsIdentifiedDetail - technicalContactsIdentifiedDetail"))
}

// TechnicalContactsIdentifiedNote is the resolver for the technicalContactsIdentifiedNote field.
func (r *iDDOCQuestionnaireResolver) TechnicalContactsIdentifiedNote(ctx context.Context, obj *models.IDDOCQuestionnaire) (*string, error) {
	panic(fmt.Errorf("not implemented: TechnicalContactsIdentifiedNote - technicalContactsIdentifiedNote"))
}

// CaptureParticipantInfo is the resolver for the captureParticipantInfo field.
func (r *iDDOCQuestionnaireResolver) CaptureParticipantInfo(ctx context.Context, obj *models.IDDOCQuestionnaire) (*bool, error) {
	panic(fmt.Errorf("not implemented: CaptureParticipantInfo - captureParticipantInfo"))
}

// CaptureParticipantInfoNote is the resolver for the captureParticipantInfoNote field.
func (r *iDDOCQuestionnaireResolver) CaptureParticipantInfoNote(ctx context.Context, obj *models.IDDOCQuestionnaire) (*string, error) {
	panic(fmt.Errorf("not implemented: CaptureParticipantInfoNote - captureParticipantInfoNote"))
}

// DraftIcdDueDate is the resolver for the draftIcdDueDate field.
func (r *iDDOCQuestionnaireResolver) DraftIcdDueDate(ctx context.Context, obj *models.IDDOCQuestionnaire) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: DraftIcdDueDate - draftIcdDueDate"))
}

// IcdNote is the resolver for the icdNote field.
func (r *iDDOCQuestionnaireResolver) IcdNote(ctx context.Context, obj *models.IDDOCQuestionnaire) (*string, error) {
	panic(fmt.Errorf("not implemented: IcdNote - icdNote"))
}

// UatNeeds is the resolver for the uatNeeds field.
func (r *iDDOCQuestionnaireResolver) UatNeeds(ctx context.Context, obj *models.IDDOCQuestionnaire) (*string, error) {
	panic(fmt.Errorf("not implemented: UatNeeds - uatNeeds"))
}

// StcNeeds is the resolver for the stcNeeds field.
func (r *iDDOCQuestionnaireResolver) StcNeeds(ctx context.Context, obj *models.IDDOCQuestionnaire) (*string, error) {
	panic(fmt.Errorf("not implemented: StcNeeds - stcNeeds"))
}

// TestingNote is the resolver for the testingNote field.
func (r *iDDOCQuestionnaireResolver) TestingNote(ctx context.Context, obj *models.IDDOCQuestionnaire) (*string, error) {
	panic(fmt.Errorf("not implemented: TestingNote - testingNote"))
}

// DataMonitoringFileTypes is the resolver for the dataMonitoringFileTypes field.
func (r *iDDOCQuestionnaireResolver) DataMonitoringFileTypes(ctx context.Context, obj *models.IDDOCQuestionnaire) ([]models.IDDOCFileType, error) {
	panic(fmt.Errorf("not implemented: DataMonitoringFileTypes - dataMonitoringFileTypes"))
}

// DataMonitoringFileOther is the resolver for the dataMonitoringFileOther field.
func (r *iDDOCQuestionnaireResolver) DataMonitoringFileOther(ctx context.Context, obj *models.IDDOCQuestionnaire) (*string, error) {
	panic(fmt.Errorf("not implemented: DataMonitoringFileOther - dataMonitoringFileOther"))
}

// DataResponseType is the resolver for the dataResponseType field.
func (r *iDDOCQuestionnaireResolver) DataResponseType(ctx context.Context, obj *models.IDDOCQuestionnaire) (*string, error) {
	panic(fmt.Errorf("not implemented: DataResponseType - dataResponseType"))
}

// DataResponseFileFrequency is the resolver for the dataResponseFileFrequency field.
func (r *iDDOCQuestionnaireResolver) DataResponseFileFrequency(ctx context.Context, obj *models.IDDOCQuestionnaire) (*string, error) {
	panic(fmt.Errorf("not implemented: DataResponseFileFrequency - dataResponseFileFrequency"))
}

// DataFullTimeOrIncremental is the resolver for the dataFullTimeOrIncremental field.
func (r *iDDOCQuestionnaireResolver) DataFullTimeOrIncremental(ctx context.Context, obj *models.IDDOCQuestionnaire) (*model.IDDOCFullTimeOrIncrementalType, error) {
	panic(fmt.Errorf("not implemented: DataFullTimeOrIncremental - dataFullTimeOrIncremental"))
}

// EftSetUp is the resolver for the eftSetUp field.
func (r *iDDOCQuestionnaireResolver) EftSetUp(ctx context.Context, obj *models.IDDOCQuestionnaire) (*bool, error) {
	panic(fmt.Errorf("not implemented: EftSetUp - eftSetUp"))
}

// DataMonitoringNote is the resolver for the dataMonitoringNote field.
func (r *iDDOCQuestionnaireResolver) DataMonitoringNote(ctx context.Context, obj *models.IDDOCQuestionnaire) (*string, error) {
	panic(fmt.Errorf("not implemented: DataMonitoringNote - dataMonitoringNote"))
}

// Status is the resolver for the status field.
func (r *iDDOCQuestionnaireResolver) Status(ctx context.Context, obj *models.IDDOCQuestionnaire) (model.IDDOCQuestionnaireStatus, error) {
	return model.IDDOCQuestionnaireStatusNotStarted, nil
	// TODO: Implement status mapping
	// panic(fmt.Errorf("not implemented: Status - status"))
}

// UpdateIDDOCQuestionnaire is the resolver for the updateIDDOCQuestionnaire field.
func (r *mutationResolver) UpdateIDDOCQuestionnaire(ctx context.Context, id uuid.UUID, changes model.IDDOCQuestionnaireChanges) (*models.IDDOCQuestionnaire, error) {
	panic(fmt.Errorf("not implemented: UpdateIDDOCQuestionnaire - updateIDDOCQuestionnaire"))
}

// CompleteIDDOCQuestionnaire is the resolver for the completeIDDOCQuestionnaire field.
func (r *mutationResolver) CompleteIDDOCQuestionnaire(ctx context.Context, id uuid.UUID) (*models.IDDOCQuestionnaire, error) {
	panic(fmt.Errorf("not implemented: CompleteIDDOCQuestionnaire - completeIDDOCQuestionnaire"))
}

// IDDOCQuestionnaire returns generated.IDDOCQuestionnaireResolver implementation.
func (r *Resolver) IDDOCQuestionnaire() generated.IDDOCQuestionnaireResolver {
	return &iDDOCQuestionnaireResolver{r}
}

type iDDOCQuestionnaireResolver struct{ *Resolver }
