package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/appcontext"
	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/graph/model"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// DataMonitoringFileTypes is the resolver for the dataMonitoringFileTypes field.
func (r *iDDOCQuestionnaireResolver) DataMonitoringFileTypes(ctx context.Context, obj *models.IDDOCQuestionnaire) ([]models.IDDOCFileType, error) {
	return obj.DataMonitoringFileTypes, nil
}

// DataFullTimeOrIncremental is the resolver for the dataFullTimeOrIncremental field.
func (r *iDDOCQuestionnaireResolver) DataFullTimeOrIncremental(ctx context.Context, obj *models.IDDOCQuestionnaire) (*model.IDDOCFullTimeOrIncrementalType, error) {
	if obj.DataFullTimeOrIncremental == nil {
		return nil, nil
	}
	value := model.IDDOCFullTimeOrIncrementalType(*obj.DataFullTimeOrIncremental)
	return &value, nil
}

// Needed is the resolver for the needed convenience field.
func (r *iDDOCQuestionnaireResolver) Needed(ctx context.Context, obj *models.IDDOCQuestionnaire) (bool, error) {
	// Questionnaire is needed if status is anything other than NOT_NEEDED
	return obj.Status != "NOT_NEEDED", nil
}

// IsIDDOCQuestionnaireComplete is the resolver for the isIDDOCQuestionnaireComplete convenience field.
func (r *iDDOCQuestionnaireResolver) IsIDDOCQuestionnaireComplete(ctx context.Context, obj *models.IDDOCQuestionnaire) (bool, error) {
	// Questionnaire is complete if status is COMPLETED
	return obj.Status == "COMPLETED", nil
}

// Status is the resolver for the status field.
func (r *iDDOCQuestionnaireResolver) Status(ctx context.Context, obj *models.IDDOCQuestionnaire) (model.IDDOCQuestionnaireStatus, error) {
	return model.IDDOCQuestionnaireStatus(obj.Status), nil
}

// UpdateIDDOCQuestionnaire is the resolver for the updateIDDOCQuestionnaire field.
func (r *mutationResolver) UpdateIDDOCQuestionnaire(ctx context.Context, id uuid.UUID, changes map[string]any) (*models.IDDOCQuestionnaire, error) {
	logger := appcontext.ZLogger(ctx)
	principal := appcontext.Principal(ctx)

	return IDDOCQuestionnaireUpdate(
		ctx,
		logger,
		id,
		changes,
		principal,
		r.store,
		r.emailService,
		r.addressBook,
	)
}

// IDDOCQuestionnaire returns generated.IDDOCQuestionnaireResolver implementation.
func (r *Resolver) IDDOCQuestionnaire() generated.IDDOCQuestionnaireResolver {
	return &iDDOCQuestionnaireResolver{r}
}

type iDDOCQuestionnaireResolver struct{ *Resolver }
