package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/appcontext"
	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/graph/model"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// KeyContacts is the resolver for the keyContacts field.
func (r *keyContactCategoryResolver) KeyContacts(ctx context.Context, obj *models.KeyContactCategory) ([]*model.KeyContact, error) {
	panic(fmt.Errorf("not implemented: KeyContacts - keyContacts"))
}

// CreateKeyContactCategory is the resolver for the createKeyContactCategory field.
func (r *mutationResolver) CreateKeyContactCategory(ctx context.Context, category string) (*models.KeyContactCategory, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)
	return CreateKeyContactCategory(ctx, logger, principal, r.store, category)
}

// UpdateKeyContactCategory is the resolver for the updateKeyContactCategory field.
func (r *mutationResolver) UpdateKeyContactCategory(ctx context.Context, id uuid.UUID, changes map[string]any) (*models.KeyContactCategory, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)
	return UpdateKeyContactCategory(ctx, logger, principal, r.store, id, changes)
}

// DeleteKeyContactCategory is the resolver for the deleteKeyContactCategory field.
func (r *mutationResolver) DeleteKeyContactCategory(ctx context.Context, id uuid.UUID) (*models.KeyContactCategory, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)
	return DeleteKeyContactCategory(ctx, logger, principal, r.store, id)
}

// KeyContactCategory is the resolver for the keyContactCategory field.
func (r *queryResolver) KeyContactCategory(ctx context.Context) ([]*models.KeyContactCategory, error) {
	logger := appcontext.ZLogger(ctx)
	return GetAllKeyContactCategories(ctx, logger, r.store)
}

// KeyContactCategoryByID is the resolver for the keyContactCategoryById field.
func (r *queryResolver) KeyContactCategoryByID(ctx context.Context, id uuid.UUID) (*models.KeyContactCategory, error) {
	panic(fmt.Errorf("not implemented: KeyContactCategoryByID - keyContactCategoryById"))
}

// KeyContactCategoriesByIds is the resolver for the keyContactCategoriesByIds field.
func (r *queryResolver) KeyContactCategoriesByIds(ctx context.Context, ids []uuid.UUID) ([]*models.KeyContactCategory, error) {
	panic(fmt.Errorf("not implemented: KeyContactCategoriesByIds - keyContactCategoriesByIds"))
}

// KeyContactCategory returns generated.KeyContactCategoryResolver implementation.
func (r *Resolver) KeyContactCategory() generated.KeyContactCategoryResolver {
	return &keyContactCategoryResolver{r}
}

type keyContactCategoryResolver struct{ *Resolver }
