package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/appcontext"
	"github.com/cms-enterprise/mint-app/pkg/models"
	"github.com/cms-enterprise/mint-app/pkg/userhelpers"
)

// CreateKeyContactMailbox is the resolver for the createKeyContactMailbox field.
func (r *mutationResolver) CreateKeyContactMailbox(ctx context.Context, mailboxTitle string, mailboxAddress string, isTeam bool, subjectArea string, subjectCategoryID uuid.UUID) (*models.KeyContact, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)

	return CreateKeyContactMailbox(ctx, logger, principal, r.store, r.emailService, r.emailTemplateService, r.addressBook, mailboxTitle, mailboxAddress, isTeam, subjectArea, subjectCategoryID)
}

// CreateKeyContactUser is the resolver for the createKeyContactUser field.
func (r *mutationResolver) CreateKeyContactUser(ctx context.Context, userName string, isTeam bool, subjectArea string, subjectCategoryID uuid.UUID) (*models.KeyContact, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)

	return CreateKeyContactUser(ctx, logger, principal, r.store, r.emailService, r.emailTemplateService, r.addressBook, userName, isTeam, subjectArea, subjectCategoryID, userhelpers.GetUserInfoAccountInfoWrapperFunc(r.service.FetchUserInfo))
}

// UpdateKeyContact is the resolver for the updateKeyContact field.
func (r *mutationResolver) UpdateKeyContact(ctx context.Context, id uuid.UUID, changes map[string]any) (*models.KeyContact, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)

	return UpdateKeyContact(ctx, logger, principal, r.store, r.emailService, r.emailTemplateService, r.addressBook, id, changes)
}

// DeleteKeyContact is the resolver for the deleteKeyContact field.
func (r *mutationResolver) DeleteKeyContact(ctx context.Context, id uuid.UUID) (*models.KeyContact, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)

	return DeleteKeyContact(ctx, logger, principal, r.store, r.emailService, r.emailTemplateService, r.addressBook, id)
}

// KeyContact is the resolver for the keyContact field.
func (r *queryResolver) KeyContact(ctx context.Context, id uuid.UUID) (*models.KeyContact, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)

	return GetKeyContact(ctx, logger, principal, r.store, id)
}
