package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/appcontext"
	"github.com/cms-enterprise/mint-app/pkg/graph/model"
)

// CreateKeyContactCategory is the resolver for the createKeyContactCategory field.
func (r *mutationResolver) CreateKeyContactCategory(ctx context.Context, category string) (*model.KeyContactCategory, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)
	return CreateKeyContactCategory(ctx, logger, principal, r.store, category)
}

// UpdateKeyContactCategory is the resolver for the updateKeyContactCategory field.
func (r *mutationResolver) UpdateKeyContactCategory(ctx context.Context, id uuid.UUID, changes map[string]any) (*model.KeyContactCategory, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)
	return UpdateKeyContactCategory(ctx, logger, principal, r.store, id, changes)
}

// DeleteKeyContactCategory is the resolver for the deleteKeyContactCategory field.
func (r *mutationResolver) DeleteKeyContactCategory(ctx context.Context, id uuid.UUID) (*model.KeyContactCategory, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)
	return DeleteKeyContactCategory(ctx, logger, principal, r.store, id)
}

// KeyContactCategory is the resolver for the keyContactCategory field.
func (r *queryResolver) KeyContactCategory(ctx context.Context) ([]*model.KeyContactCategory, error) {
	logger := appcontext.ZLogger(ctx)
	return GetAllKeyContactCategories(ctx, logger, r.store)
}
