package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/cms-enterprise/mint-app/pkg/models"
)

// ModelPlansByStatusGroup is the resolver for the modelPlansByStatusGroup field.
func (r *queryResolver) ModelPlansByStatusGroup(ctx context.Context, statusGroup models.ModelPlanStatusGroup) ([]*models.ModelPlan, error) {
	return ModelPlansByStatusLOADER(ctx, statusGroup)
}
