package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/graph/model"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// Categories is the resolver for the categories field.
func (r *modelsToOperationMatrixResolver) Categories(ctx context.Context, obj *models.ModelsToOperationMatrix) ([]*models.MTOCategory, error) {
	return MTOCategoryGetByModelPlanIDLOADER(ctx, obj.ModelPlan.ID)
}

// CommonMilestones is the resolver for the commonMilestones field.
func (r *modelsToOperationMatrixResolver) CommonMilestones(ctx context.Context, obj *models.ModelsToOperationMatrix) ([]*models.MTOCommonMilestone, error) {
	return MTOCommonMilestoneGetByModelPlanIDLOADER(ctx, &obj.ModelPlan.ID)
}

// CommonSolutions is the resolver for the commonSolutions field.
func (r *modelsToOperationMatrixResolver) CommonSolutions(ctx context.Context, obj *models.ModelsToOperationMatrix) ([]*models.MTOCommonSolution, error) {
	return MTOCommonSolutionGetByModelPlanIDLOADER(ctx, &obj.ModelPlan.ID)
}

// Milestones is the resolver for the milestones field.
func (r *modelsToOperationMatrixResolver) Milestones(ctx context.Context, obj *models.ModelsToOperationMatrix) ([]*models.MTOMilestone, error) {
	return MTOMilestoneGetByModelPlanIDLOADER(ctx, obj.ModelPlan.ID)
}

// Solutions is the resolver for the solutions field.
func (r *modelsToOperationMatrixResolver) Solutions(ctx context.Context, obj *models.ModelsToOperationMatrix) ([]*model.MTOSolution, error) {
	panic(fmt.Errorf("not implemented: Solutions - solutions"))
}

// Status is the resolver for the status field.
func (r *modelsToOperationMatrixResolver) Status(ctx context.Context, obj *models.ModelsToOperationMatrix) (models.MTOStatus, error) {
	//TODO (mto) Update when we have a methodology for Ready for Review
	mtoMarkedReadyToReview := false
	return MTOStatusGet(ctx, obj.ModelPlan.ID, mtoMarkedReadyToReview)
}

// RecentEdit is the resolver for the recentEdit field.
func (r *modelsToOperationMatrixResolver) RecentEdit(ctx context.Context, obj *models.ModelsToOperationMatrix) (*models.RecentModification, error) {
	// TODO re-visit when solutions are implemented
	// TODO re-visit when change history is implemented for MTO
	return MTOLastUpdatedGet(ctx, obj.ModelPlan.ID)
}

// Info is the resolver for the info field.
func (r *modelsToOperationMatrixResolver) Info(ctx context.Context, obj *models.ModelsToOperationMatrix) (*models.MTOInfo, error) {
	panic(fmt.Errorf("not implemented: Info - info"))
}

// MarkMTOReadyForReview is the resolver for the markMTOReadyForReview field.
func (r *mutationResolver) MarkMTOReadyForReview(ctx context.Context, id uuid.UUID, readyForReview bool) (*models.ModelsToOperationMatrix, error) {
	panic(fmt.Errorf("not implemented: MarkMTOReadyForReview - markMTOReadyForReview"))
}

// ModelsToOperationMatrix returns generated.ModelsToOperationMatrixResolver implementation.
func (r *Resolver) ModelsToOperationMatrix() generated.ModelsToOperationMatrixResolver {
	return &modelsToOperationMatrixResolver{r}
}

type modelsToOperationMatrixResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *modelsToOperationMatrixResolver) Mto(ctx context.Context, obj *models.ModelsToOperationMatrix) (*models.MTOInfo, error) {
	panic(fmt.Errorf("not implemented: Mto - mto"))
}
