package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// IsSuggested is the resolver for the isSuggested field.
func (r *mTOCommonMilestoneResolver) IsSuggested(ctx context.Context, obj *models.MTOCommonMilestone) (bool, error) {
	panic(fmt.Errorf("not implemented: IsSuggested - isSuggested"))
}

// CommonSolutions is the resolver for the commonSolutions field.
func (r *mTOCommonMilestoneResolver) CommonSolutions(ctx context.Context, obj *models.MTOCommonMilestone) ([]*models.MTOCommonSolution, error) {
	return MTOCommonSolutionGetByCommonMilestoneKeyLOADER(ctx, obj.Key)
}

// MtoCommonMilestone is the resolver for the mtoCommonMilestone field.
func (r *queryResolver) MtoCommonMilestone(ctx context.Context, key models.MTOCommonMilestoneKey) (*models.MTOCommonMilestone, error) {
	return MTOCommonMilestoneGetByKeyLOADER(ctx, key)
}

// MTOCommonMilestone returns generated.MTOCommonMilestoneResolver implementation.
func (r *Resolver) MTOCommonMilestone() generated.MTOCommonMilestoneResolver {
	return &mTOCommonMilestoneResolver{r}
}

type mTOCommonMilestoneResolver struct{ *Resolver }
