package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/mappings"
	"github.com/cms-enterprise/mint-app/pkg/appcontext"
	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/graph/model"
	"github.com/cms-enterprise/mint-app/pkg/models"
	"github.com/cms-enterprise/mint-app/pkg/storage"
)

// FacilitatedByRole is the resolver for the facilitatedByRole field.
func (r *mTOCommonMilestoneResolver) FacilitatedByRole(ctx context.Context, obj *models.MTOCommonMilestone) ([]models.MTOFacilitator, error) {
	return obj.FacilitatedByRole, nil
}

// Suggested is the resolver for the suggested field.
func (r *mTOCommonMilestoneResolver) Suggested(ctx context.Context, obj *models.MTOCommonMilestone, modelPlanID *uuid.UUID) (*model.MilestoneSuggestionReasons, error) {
	// Resolve the effective model plan ID: prefer the explicit argument, fall back to context from loader
	planID := obj.ModelPlanID
	if modelPlanID != nil {
		planID = modelPlanID
	}

	notSuggested := &model.MilestoneSuggestionReasons{
		IsSuggested: false,
		Reasons:     []*model.MilestoneSuggestionReason{},
		Count:       0,
	}

	// No model plan context or no suggestion record → not suggested
	if planID == nil || *planID == uuid.Nil || obj.MTOSuggestedMilestoneID == nil {
		return notSuggested, nil
	}

	dbReasons, err := MTOSuggestedMilestoneReasonGetByIDLOADER(ctx, *obj.MTOSuggestedMilestoneID)
	if err != nil {
		return nil, err
	}

	reasons := make([]*model.MilestoneSuggestionReason, 0, len(dbReasons))
	for _, dbReason := range dbReasons {
		t := mappings.TranslateMilestoneReason(dbReason.TriggerTable, dbReason.TriggerCol, dbReason.TriggerVal)
		reasons = append(reasons, &model.MilestoneSuggestionReason{
			Table:    models.TableName(dbReason.TriggerTable),
			Field:    dbReason.TriggerCol,
			Question: t.Question,
			Answer:   &t.Answer,
		})
	}

	return &model.MilestoneSuggestionReasons{
		IsSuggested: true,
		Reasons:     reasons,
		Count:       len(reasons),
	}, nil
}

// CommonSolutions is the resolver for the commonSolutions field.
func (r *mTOCommonMilestoneResolver) CommonSolutions(ctx context.Context, obj *models.MTOCommonMilestone) ([]*models.MTOCommonSolution, error) {
	return MTOCommonSolutionGetByCommonMilestoneIDLOADER(ctx, obj.ID)
}

// CreateMTOCommonMilestone is the resolver for the createMTOCommonMilestone field.
func (r *mutationResolver) CreateMTOCommonMilestone(ctx context.Context, name string, description string, categoryName string, subCategoryName *string, facilitatedByRole []models.MTOFacilitator, facilitatedByOther *string, mtoCommonSolutionKeys []models.MTOCommonSolutionKey) (*models.MTOCommonMilestone, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)
	principalAccount := principal.Account()
	if principalAccount == nil {
		return nil, fmt.Errorf("principal doesn't have an account, username %s", principal.String())
	}

	return CreateMTOCommonMilestone(
		logger,
		r.store,
		name,
		description,
		categoryName,
		subCategoryName,
		facilitatedByRole,
		facilitatedByOther,
		mtoCommonSolutionKeys,
		principalAccount.ID,
	)
}

// UpdateMTOCommonMilestone is the resolver for the updateMTOCommonMilestone field.
func (r *mutationResolver) UpdateMTOCommonMilestone(ctx context.Context, id uuid.UUID, changes map[string]any) (*models.MTOCommonMilestone, error) {
	panic("not implemented: UpdateMTOCommonMilestone - updateMTOCommonMilestone")
}

// ArchiveMTOCommonMilestone is the resolver for the archiveMTOCommonMilestone field.
func (r *mutationResolver) ArchiveMTOCommonMilestone(ctx context.Context, id uuid.UUID) (*models.MTOCommonMilestone, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)
	principalAccount := principal.Account()
	if principalAccount == nil {
		return nil, fmt.Errorf("principal doesn't have an account, username %s", principal.String())
	}

	return ArchiveMTOCommonMilestone(logger, r.store, id, principalAccount.ID)
}

// MtoCommonMilestones is the resolver for the mtoCommonMilestones field.
func (r *queryResolver) MtoCommonMilestones(ctx context.Context) ([]*models.MTOCommonMilestone, error) {
	return MTOCommonMilestoneGetByModelPlanIDLOADER(ctx, nil)
}

// CommonCategories is the resolver for the commonCategories field.
func (r *queryResolver) CommonCategories(ctx context.Context) ([]*models.CommonCategory, error) {
	logger := appcontext.ZLogger(ctx)
	return storage.MTOCommonMilestoneGetCommonCategories(r.store, logger)
}

// MTOCommonMilestone returns generated.MTOCommonMilestoneResolver implementation.
func (r *Resolver) MTOCommonMilestone() generated.MTOCommonMilestoneResolver {
	return &mTOCommonMilestoneResolver{r}
}

type mTOCommonMilestoneResolver struct{ *Resolver }
