package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/graph/model"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// CreateMTOCommonSolutionContractor is the resolver for the createMTOCommonSolutionContractor field.
func (r *mutationResolver) CreateMTOCommonSolutionContractor(ctx context.Context, key models.MTOCommonSolutionKey, contractorTitle *string, contractorName string) (*model.MTOCommonSolutionContractor, error) {
	panic(fmt.Errorf("not implemented: CreateMTOCommonSolutionContractor - createMTOCommonSolutionContractor"))
}

// UpdateMTOCommonSolutionContractor is the resolver for the updateMTOCommonSolutionContractor field.
func (r *mutationResolver) UpdateMTOCommonSolutionContractor(ctx context.Context, id uuid.UUID, changes map[string]interface{}) (*model.MTOCommonSolutionContractor, error) {
	panic(fmt.Errorf("not implemented: UpdateMTOCommonSolutionContractor - updateMTOCommonSolutionContractor"))
}

// DeleteMTOCommonSolutionContractor is the resolver for the deleteMTOCommonSolutionContractor field.
func (r *mutationResolver) DeleteMTOCommonSolutionContractor(ctx context.Context, id uuid.UUID) (*model.MTOCommonSolutionContractor, error) {
	panic(fmt.Errorf("not implemented: DeleteMTOCommonSolutionContractor - deleteMTOCommonSolutionContractor"))
}

// MtoCommonSolutionContractor is the resolver for the mtoCommonSolutionContractor field.
func (r *queryResolver) MtoCommonSolutionContractor(ctx context.Context, id uuid.UUID) (*model.MTOCommonSolutionContractor, error) {
	panic(fmt.Errorf("not implemented: MtoCommonSolutionContractor - mtoCommonSolutionContractor"))
}
