package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// Subjects is the resolver for the subjects field.
func (r *mTOCommonSolutionResolver) Subjects(ctx context.Context, obj *models.MTOCommonSolution) ([]models.MTOCommonSolutionSubject, error) {
	return obj.Subjects, nil
}

// ContactInformation is the resolver for the contactInformation field.
func (r *mTOCommonSolutionResolver) ContactInformation(ctx context.Context, obj *models.MTOCommonSolution) (*models.MTOCommonSolutionContactInformation, error) {
	return MTOCommonSolutionContactInformationGetByKeyLOADER(ctx, obj.Key)
}

// MTOCommonSolution returns generated.MTOCommonSolutionResolver implementation.
func (r *Resolver) MTOCommonSolution() generated.MTOCommonSolutionResolver {
	return &mTOCommonSolutionResolver{r}
}

type mTOCommonSolutionResolver struct{ *Resolver }
