package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/appcontext"
	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// RelatedMilestones is the resolver for the relatedMilestones field.
func (r *mTOSolutionResolver) RelatedMilestones(ctx context.Context, obj *models.MTOSolution) ([]*models.MTOMilestone, error) {
	panic(fmt.Errorf("not implemented: RelatedMilestones - relatedMilestones"))
}

// CommonSolution is the resolver for the commonSolution field.
func (r *mTOSolutionResolver) CommonSolution(ctx context.Context, obj *models.MTOSolution) (*models.MTOCommonSolution, error) {
	// If the key is nil there is no common solution
	if obj.Key == nil {
		return nil, nil
	}

	return MTOSolutionGetCommonSolutionByKeyLoader(ctx, obj.Key)
}

// CreateMTOSolutionCustom is the resolver for the createMTOSolutionCustom field.
func (r *mutationResolver) CreateMTOSolutionCustom(ctx context.Context, modelPlanID uuid.UUID, solutionType models.MTOSolutionType, facilitatedBy models.MTOFacilitator, name string, pocName string, pocEmail string) (*models.MTOSolution, error) {
	logger := appcontext.ZLogger(ctx)
	principal := appcontext.Principal(ctx)

	return MTOSolutionCreateCustom(
		logger,
		principal,
		r.store,
		modelPlanID,
		nil,
		name,
		solutionType,
		facilitatedBy,
		pocName,
		pocEmail,
	)
}

// CreateMTOSolutionCommon is the resolver for the createMTOSolutionCommon field.
func (r *mutationResolver) CreateMTOSolutionCommon(ctx context.Context, key *models.MTOCommonSolutionKey) (*models.MTOSolution, error) {
	logger := appcontext.ZLogger(ctx)
	principal := appcontext.Principal(ctx)

	return MTOSolutionCreateCommon(logger, principal, r.store, key)
}

// UpdateMTOSolution is the resolver for the updateMTOSolution field.
func (r *mutationResolver) UpdateMTOSolution(ctx context.Context, id uuid.UUID, changes map[string]interface{}) (*models.MTOSolution, error) {
	logger := appcontext.ZLogger(ctx)
	principal := appcontext.Principal(ctx)

	return MTOSolutionUpdate(logger, principal, r.store, id, changes)
}

// MTOSolution returns generated.MTOSolutionResolver implementation.
func (r *Resolver) MTOSolution() generated.MTOSolutionResolver { return &mTOSolutionResolver{r} }

type mTOSolutionResolver struct{ *Resolver }
