package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/cms-enterprise/mint-app/pkg/authentication"
	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/graph/model"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// UserAccount is the resolver for the userAccount field.
func (r *mTOCommonSolutionContactResolver) UserAccount(ctx context.Context, obj *models.MTOCommonSolutionContact) (*authentication.UserAccount, error) {
	panic(fmt.Errorf("not implemented: UserAccount - userAccount"))
}

// Contractors is the resolver for the contractors field.
func (r *mTOCommonSolutionContactInformationResolver) Contractors(ctx context.Context, obj *models.MTOCommonSolutionContactInformation) ([]*model.MTOCommonSolutionContractor, error) {
	panic(fmt.Errorf("not implemented: Contractors - contractors"))
}

// MTOCommonSolutionContact returns generated.MTOCommonSolutionContactResolver implementation.
func (r *Resolver) MTOCommonSolutionContact() generated.MTOCommonSolutionContactResolver {
	return &mTOCommonSolutionContactResolver{r}
}

// MTOCommonSolutionContactInformation returns generated.MTOCommonSolutionContactInformationResolver implementation.
func (r *Resolver) MTOCommonSolutionContactInformation() generated.MTOCommonSolutionContactInformationResolver {
	return &mTOCommonSolutionContactInformationResolver{r}
}

type mTOCommonSolutionContactResolver struct{ *Resolver }
type mTOCommonSolutionContactInformationResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *mTOCommonSolutionContactResolver) Account(ctx context.Context, obj *models.MTOCommonSolutionContact) (*authentication.UserAccount, error) {
	panic(fmt.Errorf("not implemented: Account - account"))
}
