package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/models"
)

// MtoCommonMilestoneDummy is the resolver for the mtoCommonMilestoneDummy field.
func (r *queryResolver) MtoCommonMilestoneDummy(ctx context.Context, id uuid.UUID) (*models.MTOCommonMilestone, error) {
	panic(fmt.Errorf("not implemented: MtoCommonMilestoneDummy - mtoCommonMilestoneDummy"))
}
