package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/cmsgov/mint-app/pkg/appcontext"
	"github.com/cmsgov/mint-app/pkg/graph/model"
	"github.com/cmsgov/mint-app/pkg/models"
)

// StatusPlannedActiveOrEnded is the resolver for the statusPlannedActiveOrEnded field.
func (r *modelPlanResolver) StatusPlannedActiveOrEnded(ctx context.Context, obj *models.ModelPlan) (model.StatusPlannedActiveOrEnded, error) {
	switch obj.Status {
	case models.ModelStatusActive:
		return model.StatusPlannedActiveOrEndedActive, nil
	case models.ModelStatusEnded:
		return model.StatusPlannedActiveOrEndedEnded, nil
	default:
		return model.StatusPlannedActiveOrEndedPlanned, nil
	}
}

// ModelPlansByOperationalSolutionKey is the resolver for the modelPlansByOperationalSolutionKey field.
func (r *queryResolver) ModelPlansByOperationalSolutionKey(ctx context.Context, operationalSolutionKey models.OperationalSolutionKey) ([]*model.ModelPlanAndOperationalSolution, error) {
	logger := appcontext.ZLogger(ctx)

	return ModelPlansByOperationalSolutionKey(
		logger,
		r.store,
		operationalSolutionKey,
	)
}
