package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/appcontext"
	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/graph/model"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// MarkPlanTaskComplete is the resolver for the markPlanTaskComplete field.
func (r *mutationResolver) MarkPlanTaskComplete(ctx context.Context, modelPlanID uuid.UUID, key models.PlanTaskKey, isComplete bool) (*models.PlanTask, error) {
	principal := appcontext.Principal(ctx)
	logger := appcontext.ZLogger(ctx)
	return PlanTaskMarkComplete(ctx, logger, modelPlanID, key, isComplete, principal, r.store, r.emailService, r.addressBook)
}

// State is the resolver for the state field.
func (r *planTaskResolver) State(ctx context.Context, obj *models.PlanTask) (model.PlanTaskState, error) {
	if obj == nil {
		return model.PlanTaskStateToDo, nil
	}
	if obj.Status == models.PlanTaskStatusComplete {
		return model.PlanTaskStateComplete, nil
	}
	return model.PlanTaskStateToDo, nil
}

// PlanTask returns generated.PlanTaskResolver implementation.
func (r *Resolver) PlanTask() generated.PlanTaskResolver { return &planTaskResolver{r} }

type planTaskResolver struct{ *Resolver }
