package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/cms-enterprise/mint-app/pkg/authentication"
	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/graph/model"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// State is the resolver for the state field.
func (r *planTaskResolver) State(ctx context.Context, obj *models.PlanTask) (model.PlanTaskState, error) {
	if obj == nil {
		return model.PlanTaskStateToDo, nil
	}
	if obj.Status == models.PlanTaskStatusComplete {
		return model.PlanTaskStateComplete, nil
	}
	return model.PlanTaskStateToDo, nil
}

// CompletedByUserAccount is the resolver for the completedByUserAccount field.
func (r *planTaskResolver) CompletedByUserAccount(ctx context.Context, obj *models.PlanTask) (*authentication.UserAccount, error) {
	return nil, nil
}

// CreatedByUserAccount is the resolver for the createdByUserAccount field.
func (r *planTaskResolver) CreatedByUserAccount(ctx context.Context, obj *models.PlanTask) (*authentication.UserAccount, error) {
	// Stub: return empty account so frontend can test until user loader is wired.
	return &authentication.UserAccount{}, nil
}

// ModifiedByUserAccount is the resolver for the modifiedByUserAccount field.
func (r *planTaskResolver) ModifiedByUserAccount(ctx context.Context, obj *models.PlanTask) (*authentication.UserAccount, error) {
	return nil, nil
}

// PlanTask returns generated.PlanTaskResolver implementation.
func (r *Resolver) PlanTask() generated.PlanTaskResolver { return &planTaskResolver{r} }

type planTaskResolver struct{ *Resolver }
