package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/cmsgov/mint-app/pkg/graph/generated"
	"github.com/cmsgov/mint-app/pkg/models"
)

// IsPrimary is the resolver for the isPrimary field.
func (r *possibleOperationalSolutionContactResolver) IsPrimary(ctx context.Context, obj *models.PossibleOperationalSolutionContact) (bool, error) {
	panic(fmt.Errorf("not implemented: IsPrimary - isPrimary"))
}

// PossibleOperationalSolutionContact returns generated.PossibleOperationalSolutionContactResolver implementation.
func (r *Resolver) PossibleOperationalSolutionContact() generated.PossibleOperationalSolutionContactResolver {
	return &possibleOperationalSolutionContactResolver{r}
}

type possibleOperationalSolutionContactResolver struct{ *Resolver }
