package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// CommonWaiver is the resolver for the commonWaiver field.
func (r *suggestedWaiverResolver) CommonWaiver(ctx context.Context, obj *models.SuggestedWaiver) (*models.CommonWaiver, error) {
	return CommonWaiverGetByID(ctx, obj.CommonWaiverID)
}

// SuggestedWaiver returns generated.SuggestedWaiverResolver implementation.
func (r *Resolver) SuggestedWaiver() generated.SuggestedWaiverResolver {
	return &suggestedWaiverResolver{r}
}

type suggestedWaiverResolver struct{ *Resolver }
