package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/google/uuid"

	"github.com/cmsgov/mint-app/pkg/models"
)

// TranslatedAuditChangeCollection is the resolver for the translatedAuditChangeCollection field.
func (r *queryResolver) TranslatedAuditChangeCollection(ctx context.Context, modelPlanID uuid.UUID) ([]*models.TranslatedAuditChange, error) {
	return TranslatedAuditChangeCollectionGetByModelPlanID(r.store, modelPlanID)
}
