package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/cmsgov/mint-app/pkg/graph/generated"
	"github.com/cmsgov/mint-app/pkg/models"
)

// ExportOptions is the resolver for the exportOptions field.
func (r *translationFieldWithOptionsResolver) ExportOptions(ctx context.Context, obj *models.TranslationFieldWithOptions) (map[string]interface{}, error) {
	panic(fmt.Errorf("not implemented: ExportOptions - exportOptions"))
}

// ExportOptions is the resolver for the exportOptions field.
func (r *translationFieldWithOptionsAndChildrenResolver) ExportOptions(ctx context.Context, obj *models.TranslationFieldWithOptionsAndChildren) (map[string]interface{}, error) {
	panic(fmt.Errorf("not implemented: ExportOptions - exportOptions"))
}

// ChildRelation is the resolver for the childRelation field.
func (r *translationFieldWithOptionsAndChildrenResolver) ChildRelation(ctx context.Context, obj *models.TranslationFieldWithOptionsAndChildren) (map[string]interface{}, error) {
	// Changes: (Translations) We don't actually use this, but leaving it here for safety
	resultMap := make(map[string]interface{})
	for key, value := range obj.ChildRelation {
		resultMap[key] = value
	}
	return resultMap, nil
}

// ExportOptions is the resolver for the exportOptions field.
func (r *translationFieldWithOptionsAndParentResolver) ExportOptions(ctx context.Context, obj *models.TranslationFieldWithOptionsAndParent) (map[string]interface{}, error) {
	panic(fmt.Errorf("not implemented: ExportOptions - exportOptions"))
}

// ExportOptions is the resolver for the exportOptions field.
func (r *translationFieldWithParentAndChildrenResolver) ExportOptions(ctx context.Context, obj *models.TranslationFieldWithParentAndChildren) (map[string]interface{}, error) {
	panic(fmt.Errorf("not implemented: ExportOptions - exportOptions"))
}

// ChildRelation is the resolver for the childRelation field.
func (r *translationFieldWithParentAndChildrenResolver) ChildRelation(ctx context.Context, obj *models.TranslationFieldWithParentAndChildren) (map[string]interface{}, error) {
	// Changes: (Translations) We don't actually use this, but leaving it here for safety
	resultMap := make(map[string]interface{})
	for key, value := range obj.ChildRelation {
		resultMap[key] = value
	}
	return resultMap, nil
}

// TranslationFieldWithOptions returns generated.TranslationFieldWithOptionsResolver implementation.
func (r *Resolver) TranslationFieldWithOptions() generated.TranslationFieldWithOptionsResolver {
	return &translationFieldWithOptionsResolver{r}
}

// TranslationFieldWithOptionsAndChildren returns generated.TranslationFieldWithOptionsAndChildrenResolver implementation.
func (r *Resolver) TranslationFieldWithOptionsAndChildren() generated.TranslationFieldWithOptionsAndChildrenResolver {
	return &translationFieldWithOptionsAndChildrenResolver{r}
}

// TranslationFieldWithOptionsAndParent returns generated.TranslationFieldWithOptionsAndParentResolver implementation.
func (r *Resolver) TranslationFieldWithOptionsAndParent() generated.TranslationFieldWithOptionsAndParentResolver {
	return &translationFieldWithOptionsAndParentResolver{r}
}

// TranslationFieldWithParentAndChildren returns generated.TranslationFieldWithParentAndChildrenResolver implementation.
func (r *Resolver) TranslationFieldWithParentAndChildren() generated.TranslationFieldWithParentAndChildrenResolver {
	return &translationFieldWithParentAndChildrenResolver{r}
}

type translationFieldWithOptionsResolver struct{ *Resolver }
type translationFieldWithOptionsAndChildrenResolver struct{ *Resolver }
type translationFieldWithOptionsAndParentResolver struct{ *Resolver }
type translationFieldWithParentAndChildrenResolver struct{ *Resolver }
