package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/google/uuid"

	"github.com/cmsgov/mint-app/pkg/graph/generated"
	"github.com/cmsgov/mint-app/pkg/models"
)

// TranslatedAuditChangeCollection is the resolver for the translatedAuditChangeCollection field.
func (r *queryResolver) TranslatedAuditChangeCollection(ctx context.Context, modelPlanID uuid.UUID) ([]*models.TranslatedAuditChange, error) {
	return TranslatedAuditChangeCollectionGetByModelPlanID(r.store, modelPlanID)
}

// TranslatedFields is the resolver for the translatedFields field.
func (r *translatedAuditChangeResolver) TranslatedFields(ctx context.Context, obj *models.TranslatedAuditChange) ([]*models.TranslatedAuditField, error) {
	return TranslatedAuditFieldCollectionGetByTranslatedAuditID(r.store, obj.ID)
}

// TranslatedAuditChange returns generated.TranslatedAuditChangeResolver implementation.
func (r *Resolver) TranslatedAuditChange() generated.TranslatedAuditChangeResolver {
	return &translatedAuditChangeResolver{r}
}

type translatedAuditChangeResolver struct{ *Resolver }
