package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// WaiverInfo is the resolver for the waiverInfo field.
func (r *queryResolver) WaiverInfo(ctx context.Context, modelPlanID uuid.UUID) (*models.WaiverInfo, error) {
	return GetWaiverInfoByModelPlanID(ctx, modelPlanID)
}

// Waivers is the resolver for the waivers field.
func (r *waiverInfoResolver) Waivers(ctx context.Context, obj *models.WaiverInfo) ([]*models.Waiver, error) {
	return WaiversGetByModelPlanID(ctx, obj.ModelPlanID)
}

// WaiverInfo returns generated.WaiverInfoResolver implementation.
func (r *Resolver) WaiverInfo() generated.WaiverInfoResolver { return &waiverInfoResolver{r} }

type waiverInfoResolver struct{ *Resolver }
