package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/cms-enterprise/mint-app/pkg/appcontext"
	"github.com/cms-enterprise/mint-app/pkg/graph/generated"
	"github.com/cms-enterprise/mint-app/pkg/models"
)

// UpdateWaiver is the resolver for the updateWaiver field.
func (r *mutationResolver) UpdateWaiver(ctx context.Context, modelPlanID uuid.UUID, commonWaiverID uuid.UUID, changes map[string]any) (*models.Waiver, error) {
	logger := appcontext.ZLogger(ctx)
	principal := appcontext.Principal(ctx)

	return WaiverUpsert(logger, modelPlanID, commonWaiverID, changes, principal, r.store)
}

// UpdateSelectedWaivers is the resolver for the updateSelectedWaivers field.
func (r *mutationResolver) UpdateSelectedWaivers(ctx context.Context, modelPlanID uuid.UUID, changes []*models.WaiverSelectionInput) ([]*models.Waiver, error) {
	logger := appcontext.ZLogger(ctx)
	principal := appcontext.Principal(ctx)

	return UpdateSelectedWaivers(logger, modelPlanID, changes, principal, r.store)
}

// CommonWaiver is the resolver for the commonWaiver field.
func (r *waiverResolver) CommonWaiver(ctx context.Context, obj *models.Waiver) (*models.CommonWaiver, error) {
	return CommonWaiverGetByID(ctx, obj.CommonWaiverID)
}

// UsingReason is the resolver for the usingReason field.
func (r *waiverSelectionInputResolver) UsingReason(ctx context.Context, obj *models.WaiverSelectionInput, data *string) error {
	panic(fmt.Errorf("not implemented: UsingReason - usingReason"))
}

// Waiver returns generated.WaiverResolver implementation.
func (r *Resolver) Waiver() generated.WaiverResolver { return &waiverResolver{r} }

// WaiverSelectionInput returns generated.WaiverSelectionInputResolver implementation.
func (r *Resolver) WaiverSelectionInput() generated.WaiverSelectionInputResolver {
	return &waiverSelectionInputResolver{r}
}

type (
	waiverResolver               struct{ *Resolver }
	waiverSelectionInputResolver struct{ *Resolver }
)
