CREATE TYPE MODEL_PLAN_STATUS_HISTORIC AS ENUM
(
    'PLAN_DRAFT',
    'PLAN_COMPLETE',
    'ICIP_COMPLETE',
    'INTERNAL_CMMI_CLEARANCE',
    'CMS_CLEARANCE',
    'HHS_CLEARANCE', --This value has one seed data model
    'OMB_ASRF_CLEARANCE',
    'CLEARED',
    'ANNOUNCED',
    'PAUSED',
    'CANCELED',
    'OTHER_HISTORIC_VALUES',
    'BRAND_NEW_STATUS'
);


ALTER TABLE model_plan_history ALTER COLUMN status TYPE MODEL_PLAN_STATUS_HISTORIC USING status::TEXT::MODEL_PLAN_STATUS_HISTORIC;
