UPDATE iddoc_questionnaire
SET
    model_plan_id = :model_plan_id,
    technical_contacts_identified = :technical_contacts_identified,
    capture_participant_information = :capture_participant_information,
    icd_owner = :icd_owner,
    draft_icd_required_by = :draft_icd_required_by,
    uat_test_data_needs = :uat_test_data_needs,
    stc_test_data_needs = :stc_test_data_needs,
    testing_timelines = :testing_timelines,
    file_types = :file_types,
    response_types = :response_types,
    file_frequency = :file_frequency,
    load_type = :load_type,
    eft_connectivity_setup = :eft_connectivity_setup,
    unsolicited_adjustments_included = :unsolicited_adjustments_included,
    data_flow_diagrams_needed = :data_flow_diagrams_needed,
    produce_benefit_enhancement_files = :produce_benefit_enhancement_files,
    file_naming_conventions = :file_naming_conventions,
    needed = :needed,
    completed_by = :completed_by,
    completed_dts = :completed_dts,
    modified_by = :modified_by,
    modified_dts = CURRENT_TIMESTAMP
WHERE id = :id
RETURNING
    id,
    model_plan_id,
    technical_contacts_identified,
    capture_participant_information,
    icd_owner,
    draft_icd_required_by,
    uat_test_data_needs,
    stc_test_data_needs,
    testing_timelines,
    file_types,
    response_types,
    file_frequency,
    load_type,
    eft_connectivity_setup,
    unsolicited_adjustments_included,
    data_flow_diagrams_needed,
    produce_benefit_enhancement_files,
    file_naming_conventions,
    needed,
    completed_by,
    completed_dts,
    created_by,
    created_dts,
    modified_by,
    modified_dts;
