UPDATE iddoc_questionnaire
SET
    model_plan_id = :model_plan_id,
    technical_contacts_identified = :technical_contacts_identified,
    technical_contacts_identified_detail = :technical_contacts_identified_detail,
    technical_contacts_identified_note = :technical_contacts_identified_note,
    capture_participant_info = :capture_participant_info,
    capture_participant_info_note = :capture_participant_info_note,
    icd_owner = :icd_owner,
    draft_icd_due_date = :draft_icd_due_date,
    icd_note = :icd_note,
    uat_needs = :uat_needs,
    stc_needs = :stc_needs,
    testing_timelines = :testing_timelines,
    testing_note = :testing_note,
    data_monitoring_file_types = :data_monitoring_file_types,
    data_monitoring_file_other = :data_monitoring_file_other,
    data_response_type = :data_response_type,
    data_response_file_frequency = :data_response_file_frequency,
    data_full_time_or_incremental = :data_full_time_or_incremental,
    eft_set_up = :eft_set_up,
    unsolicited_adjustments_included = :unsolicited_adjustments_included,
    data_flow_diagrams_needed = :data_flow_diagrams_needed,
    produce_benefit_enhancement_files = :produce_benefit_enhancement_files,
    file_naming_conventions = :file_naming_conventions,
    data_monitoring_note = :data_monitoring_note,
    needed = :needed,
    is_iddoc_questionnaire_complete = :is_iddoc_questionnaire_complete,
    completed_by = :completed_by,
    completed_dts = :completed_dts,
    modified_by = :modified_by,
    modified_dts = CURRENT_TIMESTAMP
WHERE id = :id
RETURNING
    id,
    model_plan_id,
    technical_contacts_identified,
    technical_contacts_identified_detail,
    technical_contacts_identified_note,
    capture_participant_info,
    capture_participant_info_note,
    icd_owner,
    draft_icd_due_date,
    icd_note,
    uat_needs,
    stc_needs,
    testing_timelines,
    testing_note,
    data_monitoring_file_types,
    data_monitoring_file_other,
    data_response_type,
    data_response_file_frequency,
    data_full_time_or_incremental,
    eft_set_up,
    unsolicited_adjustments_included,
    data_flow_diagrams_needed,
    produce_benefit_enhancement_files,
    file_naming_conventions,
    data_monitoring_note,
    needed,
    is_iddoc_questionnaire_complete,
    completed_by,
    completed_dts,
    created_by,
    created_dts,
    modified_by,
    modified_dts;
