UPDATE iddoc_questionnaire
SET
    model_plan_id = :model_plan_id,
    technical_contacts_identified = :technical_contacts_identified,
    technical_contacts_identified_detail = :technical_contacts_identified_detail,
    technical_contacts_identified_note = :technical_contacts_identified_note,
    capture_participant_information = :capture_participant_information,
    capture_participant_info_note = :capture_participant_info_note,
    icd_owner = :icd_owner,
    draft_icd_required_by = :draft_icd_required_by,
    icd_note = :icd_note,
    uat_test_data_needs = :uat_test_data_needs,
    stc_test_data_needs = :stc_test_data_needs,
    testing_timelines = :testing_timelines,
    testing_note = :testing_note,
    file_types = :file_types,
    data_monitoring_file_other = :data_monitoring_file_other,
    response_types = :response_types,
    file_frequency = :file_frequency,
    data_full_time_or_incremental = :data_full_time_or_incremental,
    eft_connectivity_setup = :eft_connectivity_setup,
    unsolicited_adjustments_included = :unsolicited_adjustments_included,
    data_flow_diagrams_needed = :data_flow_diagrams_needed,
    produce_benefit_enhancement_files = :produce_benefit_enhancement_files,
    file_naming_conventions = :file_naming_conventions,
    data_monitoring_note = :data_monitoring_note,
    load_type = :load_type,
    needed = :needed,
    is_iddoc_questionnaire_complete = :is_iddoc_questionnaire_complete,
    completed_by = :completed_by,
    completed_dts = :completed_dts,
    modified_by = :modified_by,
    modified_dts = CURRENT_TIMESTAMP
WHERE id = :id
RETURNING
    id,
    model_plan_id,
    technical_contacts_identified,
    technical_contacts_identified_detail,
    technical_contacts_identified_note,
    capture_participant_information,
    capture_participant_info_note,
    icd_owner,
    draft_icd_required_by,
    icd_note,
    uat_test_data_needs,
    stc_test_data_needs,
    testing_timelines,
    testing_note,
    file_types,
    data_monitoring_file_other,
    response_types,
    file_frequency,
    data_full_time_or_incremental,
    eft_connectivity_setup,
    unsolicited_adjustments_included,
    data_flow_diagrams_needed,
    produce_benefit_enhancement_files,
    file_naming_conventions,
    data_monitoring_note,
    load_type,
    needed,
    is_iddoc_questionnaire_complete,
    completed_by,
    completed_dts,
    created_by,
    created_dts,
    modified_by,
    modified_dts;
