import { gql } from '@apollo/client';

export default gql(/* GraphQL */ `
  query GetAllParticipantsAndProviders($id: UUID!) {
    modelPlan(id: $id) {
      id
      participantsAndProviders {
        id
        participants
        medicareProviderType
        isNewTypeOfProvidersOrSuppliers
        statesEngagement
        participantsOther
        participantsNote
        participantsCurrentlyInModels
        participantsCurrentlyInModelsNote
        modelApplicationLevel
        expectedNumberOfParticipants
        estimateConfidence
        confidenceNote
        recruitmentMethod
        recruitmentOther
        recruitmentNote
        selectionMethod
        selectionOther
        selectionNote
        participantAddedFrequency
        participantAddedFrequencyContinually
        participantAddedFrequencyOther
        participantAddedFrequencyNote
        participantRemovedFrequency
        participantRemovedFrequencyContinually
        participantRemovedFrequencyOther
        participantRemovedFrequencyNote
        communicationMethod
        communicationMethodOther
        communicationNote
        riskType
        riskOther
        riskNote
        willRiskChange
        willRiskChangeNote
        participantRequireFinancialGuarantee
        participantRequireFinancialGuaranteeType
        participantRequireFinancialGuaranteeOther
        participantRequireFinancialGuaranteeNote
        coordinateWork
        coordinateWorkNote
        gainsharePayments
        gainsharePaymentsTrack
        gainsharePaymentsNote
        gainsharePaymentsEligibility
        gainsharePaymentsEligibilityOther
        participantsIds
        participantsIdsOther
        participantsIDSNote
        providerAdditionFrequency
        providerAdditionFrequencyContinually
        providerAdditionFrequencyOther
        providerAdditionFrequencyNote
        providerAddMethod
        providerAddMethodOther
        providerAddMethodNote
        providerLeaveMethod
        providerLeaveMethodOther
        providerLeaveMethodNote
        providerRemovalFrequency
        providerRemovalFrequencyContinually
        providerRemovalFrequencyOther
        providerRemovalFrequencyNote
        providerOverlap
        providerOverlapHierarchy
        providerOverlapNote
        createdDts
        modifiedDts
        status
      }
    }
  }
`);
