INSERT INTO existing_model_link(
    id,
    model_plan_id,
    existing_model_id,
    current_model_plan_id,
    field_name,
    created_by,
    modified_by
)
VALUES(
    :id,
    :model_plan_id,
    :existing_model_id,
    :current_model_plan_id,
    :field_name,
    :created_by,
    :modified_by
)
RETURNING
    id,
    model_plan_id,
    existing_model_id,
    current_model_plan_id,
    field_name,
    created_by,
    created_dts,
    modified_by,
    modified_dts;
