#!/usr/bin/env bash

set -eu -o pipefail

repository="$1"
image_tag="$2"
function_qualifier="$3"

payload="$(jq --null-input ".repository= \"$repository\" | .imageTag = \"$image_tag\"")"
aws lambda invoke --function-name ecr-scan-findings --cli-binary-format raw-in-base64-out --payload "$payload" --qualifier "$function_qualifier" scan_response.json
jq < scan_response.json
totalFindings="$(jq .totalFindings scan_response.json)"
if [[ "$totalFindings" != 0 ]]; then
  echo "Scan found $totalFindings findings!"
  exit 1
else
  echo "Scan found no findings"
fi
