#!/usr/bin/env bash
#

set -u

function_name="$1"
lambda_version="${2:-\$LATEST}"
service_id="$3"

cluster_id="$APP_ENV-easi-app"
payload="$(jq --null-input ".command = \"runtask\" | .body.cluster_id = \"$cluster_id\" | .body.service_id = \"$service_id\"")"
cli_read_timeout=240

if (set -x ; aws lambda invoke --qualifier "$lambda_version" --cli-read-timeout "$cli_read_timeout" --function "$function_name" --cli-binary-format raw-in-base64-out --payload "$payload" lambda_response.json) ; then
  exitCode="$(jq '.data.response.taskStatus.exitCode' < lambda_response.json)"
  if [[ "$exitCode" != 0 ]] ; then
    echo ": task exited non-zero or exit status could not be parsed" 1>&2
    exit 1
  fi
else
  exit
fi
