#!/usr/bin/env bash

# Run GraphQL generation for Go files
go generate ./... || exit

if ! command -v goimports &> /dev/null; then
  go install golang.org/x/tools/cmd/goimports@latest || exit
fi

goimports -w -local github.com/cmsgov/easi-app pkg/graph/schema.resolvers.go || exit

# Run GraphQL generation for Typescript files
yarn generate
