#!/usr/bin/env bash
#
# run `mint` app tests
#

set -eu -o pipefail

builddir="$(git rev-parse --show-toplevel)"

red_color_code="\e[31m"
reset_color_code="\e[0m"

"$builddir"/bin/mint test

# Convert go-coverage.out to txt and html
go tool cover -func=go-coverage.out -o "go-coverage.txt"
go tool cover -html=go-coverage.out -o "go-coverage.html"
# parse out the total coverage percentage which is on the line with (statements) and strip off the % sign
# https://unix.stackexchange.com/questions/305190/remove-last-character-from-string-captured-with-awk
percent=$(grep '(statements)' "go-coverage.txt" | awk '{print substr($NF, 1, length($NF)-1)}')
goal_percent=0 # We don't want to block on coverage for now -- just report coverage %

# use bc to perform floating-point comparison,
# then use (( )) to have bash use an arithmetic context to interpret bc's output
# see https://stackoverflow.com/a/11238237 for this specific use case
# also see https://stackoverflow.com/a/49716000 for background - "The result code of an arithmetic expression is 0 if the result of the arithmetic evaluation was not 0 (or an error)."
if ((  $(echo "$percent >= $goal_percent" | bc -l) )); then
    # coverage is good
    echo "total coverage is ${percent}%"
else
    # coverage is under goal
    echo -e "${red_color_code}total coverage has dropped to ${percent}%; needs to be at least ${goal_percent}%${reset_color_code}"
    # fail build
    exit 1
fi

if [[ -d "results" ]]; then
    mv go-coverage.* results/
else
    mkdir -p results
    mv go-coverage.* results/
fi
