#!/usr/bin/env bash
#
# run `easi` app tests
#

set -eu -o pipefail

builddir="$(git rev-parse --show-toplevel)"
export EMAIL_TEMPLATE_DIR=$builddir/pkg/email/templates

red_color_code="\e[31m"
reset_color_code="\e[0m"

"$builddir"/bin/easi test

# Convert go-coverage.out to txt and html
go tool cover -func=go-coverage.out -o "go-coverage.txt"
go tool cover -html=go-coverage.out -o "go-coverage.html"
# parse out the total coverage percentage which is on the line with (statements) and strip off the % sign
# https://unix.stackexchange.com/questions/305190/remove-last-character-from-string-captured-with-awk
percent=$(grep '(statements)' "go-coverage.txt" | awk '{print substr($NF, 1, length($NF)-1)}')
goal_percent=55
# using a oneline python function to test if percent is less than goal and return a proper exit code
if python -c "exit(1) if ${percent} < ${goal_percent} else exit()"; then
    # coverage is good
    echo "total coverage is ${percent}%"
else
    # coverage is under goal
    echo -e "${red_color_code}total coverage has dropped to ${percent}%; needs to be at least ${goal_percent}%${reset_color_code}"
    # fail build
    exit 1
fi

if [[ -d "results" ]]; then
    mv go-coverage.* results/
else
    mkdir -p results
    mv go-coverage.* results/
fi
