UPDATE waiver_assessment_survey
SET
    modifies_medicare_savings_programs = :modifies_medicare_savings_programs,
    modifies_medicare_savings_programs_example = :modifies_medicare_savings_programs_example,
    modifies_medicare_savings_programs_why_not = :modifies_medicare_savings_programs_why_not,
    bundles_payments = :bundles_payments,
    bundles_payments_example = :bundles_payments_example,
    bundles_payments_why_not = :bundles_payments_why_not,
    offers_risk_sharing_arrangements = :offers_risk_sharing_arrangements,
    offers_risk_sharing_arrangements_example = :offers_risk_sharing_arrangements_example,
    offers_risk_sharing_arrangements_why_not = :offers_risk_sharing_arrangements_why_not,
    impacts_site_of_care_payments = :impacts_site_of_care_payments,
    impacts_site_of_care_payments_example = :impacts_site_of_care_payments_example,
    impacts_site_of_care_payments_why_not = :impacts_site_of_care_payments_why_not,
    modifies_care_team_scope_of_practice = :modifies_care_team_scope_of_practice,
    modifies_care_team_scope_of_practice_example = :modifies_care_team_scope_of_practice_example,
    modifies_care_team_scope_of_practice_why_not = :modifies_care_team_scope_of_practice_why_not,
    modifies_care_delivery_with_claims_based_payments = :modifies_care_delivery_with_claims_based_payments,
    modifies_care_delivery_with_claims_based_payments_example = :modifies_care_delivery_with_claims_based_payments_example,
    modifies_care_delivery_with_claims_based_payments_why_not = :modifies_care_delivery_with_claims_based_payments_why_not,
    modifies_quality_measurements_or_payments_via_waivers = :modifies_quality_measurements_or_payments_via_waivers,
    modifies_quality_measurements_or_payments_via_waivers_example = :modifies_quality_measurements_or_payments_via_waivers_example,
    modifies_quality_measurements_or_payments_via_waivers_why_not = :modifies_quality_measurements_or_payments_via_waivers_why_not,
    impacts_medicaid_only_beneficiaries = :impacts_medicaid_only_beneficiaries,
    impacts_medicaid_only_beneficiaries_example = :impacts_medicaid_only_beneficiaries_example,
    impacts_medicaid_only_beneficiaries_why_not = :impacts_medicaid_only_beneficiaries_why_not,
    impacts_home_community_based_service_payments = :impacts_home_community_based_service_payments,
    impacts_home_community_based_service_payments_example = :impacts_home_community_based_service_payments_example,
    impacts_home_community_based_service_payments_why_not = :impacts_home_community_based_service_payments_why_not,
    impacts_managed_care_waivers = :impacts_managed_care_waivers,
    impacts_managed_care_waivers_example = :impacts_managed_care_waivers_example,
    impacts_managed_care_waivers_why_not = :impacts_managed_care_waivers_why_not,
    additional_medicaid_specific_waivers = :additional_medicaid_specific_waivers,
    status = :status,
    modified_by = :modified_by,
    modified_dts = CURRENT_TIMESTAMP
WHERE id = :id
RETURNING
    id,
    model_plan_id,
    modifies_medicare_savings_programs,
    modifies_medicare_savings_programs_example,
    modifies_medicare_savings_programs_why_not,
    bundles_payments,
    bundles_payments_example,
    bundles_payments_why_not,
    offers_risk_sharing_arrangements,
    offers_risk_sharing_arrangements_example,
    offers_risk_sharing_arrangements_why_not,
    impacts_site_of_care_payments,
    impacts_site_of_care_payments_example,
    impacts_site_of_care_payments_why_not,
    modifies_care_team_scope_of_practice,
    modifies_care_team_scope_of_practice_example,
    modifies_care_team_scope_of_practice_why_not,
    modifies_care_delivery_with_claims_based_payments,
    modifies_care_delivery_with_claims_based_payments_example,
    modifies_care_delivery_with_claims_based_payments_why_not,
    modifies_quality_measurements_or_payments_via_waivers,
    modifies_quality_measurements_or_payments_via_waivers_example,
    modifies_quality_measurements_or_payments_via_waivers_why_not,
    impacts_medicaid_only_beneficiaries,
    impacts_medicaid_only_beneficiaries_example,
    impacts_medicaid_only_beneficiaries_why_not,
    impacts_home_community_based_service_payments,
    impacts_home_community_based_service_payments_example,
    impacts_home_community_based_service_payments_why_not,
    impacts_managed_care_waivers,
    impacts_managed_care_waivers_example,
    impacts_managed_care_waivers_why_not,
    additional_medicaid_specific_waivers,
    status,
    created_by,
    created_dts,
    modified_by,
    modified_dts;
