name: build_db_clean_image

on:
  schedule:
    - cron: "0 6 * * 6"

env:
  AWS_DEFAULT_REGION: us-west-2
  DOCKER_BUILDKIT: 1

jobs:
  build_db_clean_image:
    if: ${{ false }} # Disabled until we have a need for this image and can deploy / call it
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Login to Docker Hub
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: easi-db-clean
        run: |
          docker build --quiet --no-cache --tag "$ECR_REGISTRY/$ECR_REPOSITORY:latest" --file "Dockerfile.db_clean" .
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:latest"
