name: Build and Upload Frontend Assets

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
        description: Environment to build frontend assets for

env:
    GIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    ENV: ${{ inputs.env }}

permissions:
  id-token: write
  contents: read

jobs:
  build_frontend_assets:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    env:
      APP_ENV: ${{ inputs.env }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GIT_HASH }}
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Build Frontend Assets
        env:
          APP_ENV: ${{ inputs.env }}
          LD_CLIENT_ID: ${{ secrets.LD_CLIENT_ID }}
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          OKTA_SERVER_ID: ${{ secrets.OKTA_SERVER_ID }}
          STATIC_S3_BUCKET: ${{ secrets.STATIC_S3_BUCKET }}
          REACT_APP_BEACON_ID: ${{ secrets.REACT_APP_BEACON_ID }}
        run: |
          ./scripts/release_static
      - name: Upload Frontend assets
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.env }}-frontend-assets
          path: build/
          retention-days: 10
      - name: Announce failure
        if: ${{ failure() }}
        run: |
          ./scripts/github-action-announce-broken-branch