name: PR Build and Test

on:
  pull_request:
    branches:
      - "**"

# This concurrency group exists with cancel-in-progress: true so that only the latest run of the workflow is executed (as its all that should matter).
concurrency:
  group: pr-build-and-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build_Application_Images:
    uses: ./.github/workflows/build_application_images.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  Run_Tests:
    uses: ./.github/workflows/run_tests.yml
    needs: Build_Application_Images
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SES_SOURCE_ARN: ${{ secrets.AWS_SES_SOURCE_ARN }}
      OKTA_TEST_PASSWORD: ${{ secrets.OKTA_TEST_PASSWORD }}
      OKTA_TEST_SECRET: ${{ secrets.OKTA_TEST_SECRET }}
      OKTA_TEST_USERNAME: ${{ secrets.OKTA_TEST_USERNAME }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
