name: Copilot Review on PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  request-copilot-review:
    name: Request GitHub Copilot PR Review
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Copilot Review
        uses: actions/github-script@v7
        with:
          script: |
            const reviewers = ['github-copilot[bot]'];

            const pr = context.payload.pull_request;
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              reviewers,
            });
