name: Copilot Review on PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

env:
  REVIEWERS: github-copilot[bot]  # 👈 Set default reviewer(s) here, comma-separated

jobs:
  request-review:
    runs-on: ubuntu-latest
    steps:
      - name: Request Reviewers from env
        uses: actions/github-script@v8
        with:
          script: |
            try {
              const reviewers = process.env.REVIEWERS.split(',').map(r => r.trim());
              const pr = context.payload.pull_request;

              const response = await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                reviewers,
              });

              core.info(`Reviewers requested: ${reviewers.join(', ')}`);
              core.info(`GitHub API status: ${response.status}`);
            } catch (error) {
              if (error.status === 422) {
                core.warning(`Reviewer(s) may already be assigned or invalid: ${error.message}`);
              } else if (error.status === 403 || error.status === 401) {
                core.setFailed(`Permission error while requesting reviewers: ${error.message}`);
              } else {
                core.setFailed(`Unexpected error: ${error.message}`);
              }
            }
