name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit

  build_application_images:
    uses: ./.github/workflows/build_application_images.yml
    needs: run_tests
    secrets: inherit

  deploy_all:
    needs: build_application_images
    uses: ./.github/workflows/deploy_all.yml
    secrets: inherit
