name: Deploy Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-pipeline

jobs:
  run_tests:
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit

  build_frontend_assets:
    strategy:
      matrix:
        # EASI-4179: Temporary disable dev build
        # env: [dev, test, impl, prod]
        env: [test, impl, prod]
    uses: ./.github/workflows/build_frontend_assets.yml
    with:
      env: ${{ matrix.env }}
    secrets: inherit

  build_application_images:
    uses: ./.github/workflows/build_application_images.yml
    needs: run_tests
    secrets: inherit

  # EASI-4179: Temporary disable deploy_dev
  # deploy_dev:
  #   needs: [build_application_images, build_frontend_assets]
  #   uses: ./.github/workflows/deploy_to_environment.yml
  #   with:
  #     env: dev
  #   secrets: inherit

  deploy_test:
    needs: [build_application_images, build_frontend_assets]
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: test
    secrets: inherit

  deploy_impl:
    # EASI-4179: Temporary disable needs deploy_dev
    # needs: [deploy_dev, deploy_test]
    needs: deploy_test
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: impl
    secrets: inherit

  deploy_prod:
    needs: deploy_impl
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: prod
    secrets: inherit
