name: Deploy Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-pipeline

jobs:
  cache_dependencies:
    uses: ./.github/workflows/cache_dependencies.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  build_application_images:
    uses: ./.github/workflows/build_application_images.yml
    needs: cache_dependencies
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      INFRA_ROLE_TO_ASSUME: ${{ secrets.INFRA_ROLE_TO_ASSUME }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  run_tests:
    uses: ./.github/workflows/run_tests.yml
    needs: build_application_images
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy_dev:
    needs: run_tests
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: dev
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      LD_CLIENT_ID: ${{ secrets.LD_CLIENT_ID }}
      OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
      OKTA_SERVER_ID: ${{ secrets.OKTA_SERVER_ID }}
      STATIC_S3_BUCKET: ${{ secrets.STATIC_S3_BUCKET }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

  deploy_test:
    needs: deploy_dev
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: test
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      LD_CLIENT_ID: ${{ secrets.LD_CLIENT_ID }}
      OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
      OKTA_SERVER_ID: ${{ secrets.OKTA_SERVER_ID }}
      STATIC_S3_BUCKET: ${{ secrets.STATIC_S3_BUCKET }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

  deploy_impl:
    needs: deploy_test
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: impl
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      LD_CLIENT_ID: ${{ secrets.LD_CLIENT_ID }}
      OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
      OKTA_SERVER_ID: ${{ secrets.OKTA_SERVER_ID }}
      STATIC_S3_BUCKET: ${{ secrets.STATIC_S3_BUCKET }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

  deploy_prod:
    # needs: deploy_impl
    needs: deploy_test # TODO Reset to needing `deploy_impl` after pen-testing is complete! Right now, we'll base it off `deploy_test`
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: prod
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      LD_CLIENT_ID: ${{ secrets.LD_CLIENT_ID }}
      OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
      OKTA_SERVER_ID: ${{ secrets.OKTA_SERVER_ID }}
      STATIC_S3_BUCKET: ${{ secrets.STATIC_S3_BUCKET }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

  
