name: Fetch branch

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Fetch branch
        run: |
          echo "Fetching the latest version of the branch '${{ github.event.inputs.ref }}'"
          git fetch --no-tags origin "${{ github.event.inputs.ref }}:${{ github.event.inputs.ref }}"
