name: Gather Migrations

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  gather_migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Gather migration files from base branch
        run: |
          echo "Gathering ./migrations/ files from base branch '${{ inputs.base_branch }}'"
          BASE_FILES=$(git ls-tree --name-only "${{ inputs.base_branch }}" -- ./migrations/)
          echo "BASE files:"
          echo "${BASE_FILES}"

          # We need to format $MIGRATION_BASE_FILES as a heredoc so that we can use it in the next step
          echo "MIGRATION_BASE_FILES<<EOF" >> ${GITHUB_ENV}
          echo "${BASE_FILES}" >> ${GITHUB_ENV}
          echo "EOF" >> ${GITHUB_ENV}

      - name: Gather changed migration files from head branch
        run: |
          echo "Comparing head branch '${{ inputs.head_branch }}' with base branch '${{ inputs.base_branch }}'"
          echo "Gathering ./migrations/ file changes from head branch '${{ inputs.head_branch }}'"
          HEAD_MIGRATION_FILES=$(git diff --name-only "${{ inputs.base_branch }}" "${{ inputs.head_branch }}" -- ./migrations/)
          echo "HEAD changed files:"
          echo "${HEAD_MIGRATION_FILES}"

          # We need to format $MIGRATION_HEAD_FILES as a heredoc so that we can use it in the next step
          echo "MIGRATION_HEAD_FILES<<EOF" >> ${GITHUB_ENV}
          echo "${HEAD_MIGRATION_FILES}" >> ${GITHUB_ENV}
          echo "EOF" >> ${GITHUB_ENV}

      - name: Extracting prefixes from head branch
        run: |
          HEAD_PREFIXES=$(echo "${{ env.MIGRATION_HEAD_FILES }}" | awk -F'__' '{print $1}')
          echo "HEAD prefixes: '${HEAD_PREFIXES}'"
          echo "MIGRATION_HEAD_PREFIXES<<EOF" >> ${GITHUB_ENV}
          echo "${HEAD_PREFIXES}" >> ${GITHUB_ENV}
          echo "EOF" >> ${GITHUB_ENV}

      - name: Extracting prefixes from base branch
        run: |
          BASE_PREFIXES=$(echo "${{ env.MIGRATION_BASE_FILES }}" | awk -F'__' '{print $1}')
          echo "BASE prefixes: '${BASE_PREFIXES}'"
          echo "MIGRATION_BASE_PREFIXES<<EOF" >> $GITHUB_ENV
          echo "${BASE_PREFIXES}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
