name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        default: dev
        type: choice
        description: Environment to deploy to
        options:
          - dev
          - test
          - impl
          - prod
      confirm_production_deploy:
        required: true
        default: false
        type: boolean
        description: Confirm that you want to deploy to production

permissions:
  id-token: write
  contents: read

jobs:
  build_application_images:
    uses: ./.github/workflows/build_application_images.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      INFRA_ROLE_TO_ASSUME: ${{ secrets.INFRA_ROLE_TO_ASSUME }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      CONTRIBSYS_REPO_USERNAME: ${{ secrets.CONTRIBSYS_REPO_USERNAME }}
      CONTRIBSYS_REPO_PASSWORD: ${{ secrets.CONTRIBSYS_REPO_PASSWORD }}

  run_tests:
    uses: ./.github/workflows/run_tests.yml
    needs: build_application_images
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CONTRIBSYS_REPO_USERNAME: ${{ secrets.CONTRIBSYS_REPO_USERNAME }}
      CONTRIBSYS_REPO_PASSWORD: ${{ secrets.CONTRIBSYS_REPO_PASSWORD }}
      OKTA_TEST_USERNAME: ${{ secrets.OKTA_TEST_USERNAME }}
      OKTA_TEST_PASSWORD: ${{ secrets.OKTA_TEST_PASSWORD }}
      OKTA_TEST_SECRET: ${{ secrets.OKTA_TEST_SECRET }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

  deploy:
    # Only deploy if one of the two cases is true:
    # 1. We're not deploying to prod
    # 2. We're deploying to prod, and you've confirmed (with the confirm_production_deploy checkbox) that you actually mean to deploy to prod!
    if: ${{ github.event.inputs.env != 'prod' || (github.event.inputs.env == 'prod' && github.event.inputs.confirm_production_deploy == true) }}
    needs: run_tests
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: ${{ inputs.env }}
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      LD_CLIENT_ID: ${{ secrets.LD_CLIENT_ID }}
      OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
      OKTA_SERVER_ID: ${{ secrets.OKTA_SERVER_ID }}
      STATIC_S3_BUCKET: ${{ secrets.STATIC_S3_BUCKET }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
