name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        default: dev
        type: choice
        description: Environment to deploy to
        options:
          - dev
          - test
          - impl
          - prod
      confirm_production_deploy:
        required: true
        default: false
        type: boolean
        description: Confirm that you want to deploy to production

permissions:
  id-token: write
  contents: read

jobs:
  run_tests:
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit

  build_application_images:
    uses: ./.github/workflows/build_application_images.yml
    needs: [run_tests]
    secrets: inherit

  build_frontend_assets:
    uses: ./.github/workflows/build_frontend_assets.yml
    needs: [run_tests]
    secrets: inherit
    with:
      env: ${{ inputs.env }}



  deploy:
    # Only deploy if one of the two cases is true:
    # 1. We're not deploying to prod
    # 2. We're deploying to prod, and you've confirmed (with the confirm_production_deploy checkbox) that you actually mean to deploy to prod!
    if: ${{ github.event.inputs.env != 'prod' || (github.event.inputs.env == 'prod' && github.event.inputs.confirm_production_deploy == true) }}
    needs: [build_application_images, build_frontend_assets]
    uses: ./.github/workflows/deploy_to_environment.yml
    with:
      env: ${{ inputs.env }}
    secrets: inherit
