name: rescan_deployed_image

on:
  schedule:
    - cron:  '0 6 * * *' # 2300 PST, 0200 EST

env:
  AWS_DEFAULT_REGION: us-west-2
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  rescan_deployed_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Check deployed image for vulnerability findings - impl
        env: 
          APP_ENV: impl
        run: bash ./scripts/check_deployed_image_findings "easi-backend" "7"
      - name: Check deployed image for vulnerability findings - prod
        env:
          APP_ENV: prod
        run: bash ./scripts/check_deployed_image_findings "easi-backend" "7"
      - name: Announce failure
        if: ${{ failure() }}
        run: ./scripts/github-action-announce-broken-branch