import { gql } from '@apollo/client';

// This is a query to get ALL data for a single model, used for exporting/reporting features
export default gql(/* GraphQL */ `
  query GetAllSingleModelData($id: UUID!) {
    modelPlan(id: $id) {
      id
      modelName
      nameHistory(sort: DESC)
      abbreviation
      archived
      createdByUserAccount {
        commonName
      }
      createdDts
      status
      taskListStatus
      prepareForClearance {
        status
        latestClearanceDts
      }
      basics {
        id
        modelCategory
        additionalModelCategories
        amsModelID
        demoCode
        cmsCenters
        cmmiGroups
        modelType
        modelTypeOther
        problem
        goal
        testInterventions
        note
        readyForReviewByUserAccount {
          commonName
        }
        readyForReviewDts
        readyForClearanceByUserAccount {
          commonName
        }
        readyForClearanceDts
        status
      }
      generalCharacteristics {
        id
        rulemakingRequired
        rulemakingRequiredDescription
        rulemakingRequiredNote
        authorityAllowances
        authorityAllowancesOther
        authorityAllowancesNote
        waiversRequired
        waiversRequiredTypes
        waiversRequiredNote
        isNewModel
        existingModel
        resemblesExistingModel
        resemblesExistingModelWhyHow
        resemblesExistingModelHow
        resemblesExistingModelNote
        resemblesExistingModelWhich {
          names
        }
        resemblesExistingModelOtherSelected
        resemblesExistingModelOtherSpecify
        resemblesExistingModelOtherOption
        participationInModelPrecondition
        participationInModelPreconditionWhich {
          names
        }
        participationInModelPreconditionOtherSelected
        participationInModelPreconditionOtherSpecify
        participationInModelPreconditionOtherOption
        participationInModelPreconditionWhyHow
        participationInModelPreconditionNote
        hasComponentsOrTracks
        hasComponentsOrTracksDiffer
        hasComponentsOrTracksNote
        careCoordinationInvolved
        careCoordinationInvolvedDescription
        careCoordinationInvolvedNote
        additionalServicesInvolved
        additionalServicesInvolvedDescription
        additionalServicesInvolvedNote
        communityPartnersInvolved
        communityPartnersInvolvedDescription
        communityPartnersInvolvedNote
        phasedIn
        phasedInNote
        agencyOrStateHelp
        agencyOrStateHelpOther
        agencyOrStateHelpNote
        alternativePaymentModelTypes
        alternativePaymentModelNote
        keyCharacteristics
        keyCharacteristicsNote
        keyCharacteristicsOther
        collectPlanBids
        collectPlanBidsNote
        managePartCDEnrollment
        managePartCDEnrollmentNote
        planContractUpdated
        planContractUpdatedNote
        geographiesTargeted
        geographiesTargetedTypes
        geographiesStatesAndTerritories
        geographiesRegionTypes
        geographiesTargetedTypesOther
        geographiesTargetedAppliedTo
        geographiesTargetedAppliedToOther
        geographiesTargetedNote
        participationOptions
        participationOptionsNote
        agreementTypes
        agreementTypesOther
        multiplePatricipationAgreementsNeeded
        multiplePatricipationAgreementsNeededNote
        readyForReviewByUserAccount {
          commonName
        }
        readyForReviewDts
        readyForClearanceByUserAccount {
          commonName
        }
        readyForClearanceDts
        status
      }
      participantsAndProviders {
        id
        participantAddedFrequency
        participantAddedFrequencyContinually
        participantAddedFrequencyOther
        participantAddedFrequencyNote
        participantRemovedFrequency
        participantRemovedFrequencyContinually
        participantRemovedFrequencyOther
        participantRemovedFrequencyNote
        communicationMethod
        communicationMethodOther
        communicationNote
        riskType
        riskOther
        riskNote
        willRiskChange
        willRiskChangeNote
        participantRequireFinancialGuarantee
        participantRequireFinancialGuaranteeType
        participantRequireFinancialGuaranteeOther
        participantRequireFinancialGuaranteeNote
        coordinateWork
        coordinateWorkNote
        gainsharePayments
        gainsharePaymentsTrack
        gainsharePaymentsEligibility
        gainsharePaymentsEligibilityOther
        gainsharePaymentsNote
        participantsIds
        participantsIdsOther
        participantsIDSNote
        expectedNumberOfParticipants
        estimateConfidence
        confidenceNote
        recruitmentMethod
        recruitmentOther
        recruitmentNote
        selectionMethod
        selectionOther
        selectionNote
        participants
        medicareProviderType
        isNewTypeOfProvidersOrSuppliers
        statesEngagement
        participantsOther
        participantsNote
        participantsCurrentlyInModels
        participantsCurrentlyInModelsNote
        modelApplicationLevel
        providerAdditionFrequency
        providerAdditionFrequencyContinually
        providerAdditionFrequencyOther
        providerAdditionFrequencyNote
        providerAddMethod
        providerAddMethodOther
        providerAddMethodNote
        providerLeaveMethod
        providerLeaveMethodOther
        providerLeaveMethodNote
        providerRemovalFrequency
        providerRemovalFrequencyContinually
        providerRemovalFrequencyOther
        providerRemovalFrequencyNote
        providerOverlap
        providerOverlapHierarchy
        providerOverlapNote
        readyForReviewByUserAccount {
          commonName
        }
        readyForReviewDts
        readyForClearanceByUserAccount {
          commonName
        }
        readyForClearanceDts
        status
      }
      beneficiaries {
        id
        beneficiaries
        diseaseSpecificGroup
        beneficiariesNote
        beneficiariesOther
        beneficiaryOverlap
        beneficiaryOverlapNote
        beneficiarySelectionNote
        beneficiarySelectionOther
        beneficiarySelectionMethod
        treatDualElligibleDifferent
        treatDualElligibleDifferentHow
        treatDualElligibleDifferentNote
        excludeCertainCharacteristics
        excludeCertainCharacteristicsCriteria
        excludeCertainCharacteristicsNote
        beneficiarySelectionFrequency
        beneficiarySelectionFrequencyContinually
        beneficiarySelectionFrequencyNote
        beneficiarySelectionFrequencyOther
        beneficiaryRemovalFrequency
        beneficiaryRemovalFrequencyContinually
        beneficiaryRemovalFrequencyNote
        beneficiaryRemovalFrequencyOther
        precedenceRules
        precedenceRulesYes
        precedenceRulesNo
        precedenceRulesNote
        numberPeopleImpacted
        estimateConfidence
        confidenceNote
        readyForReviewByUserAccount {
          commonName
        }
        readyForReviewDts
        readyForClearanceByUserAccount {
          commonName
        }
        readyForClearanceDts
        status
      }
      opsEvalAndLearning {
        id
        ccmInvolvment
        ccmInvolvmentOther
        ccmInvolvmentNote
        iddocSupport
        iddocSupportNote
        sendFilesBetweenCcw
        sendFilesBetweenCcwNote
        appToSendFilesToKnown
        appToSendFilesToWhich
        appToSendFilesToNote
        useCcwForFileDistribiutionToParticipants
        useCcwForFileDistribiutionToParticipantsNote
        developNewQualityMeasures
        developNewQualityMeasuresNote
        qualityPerformanceImpactsPayment
        qualityPerformanceImpactsPaymentOther
        qualityPerformanceImpactsPaymentNote
        dataSharingStarts
        dataSharingStartsOther
        dataSharingFrequency
        dataSharingFrequencyContinually
        dataSharingFrequencyOther
        dataSharingStartsNote
        dataCollectionStarts
        dataCollectionStartsOther
        dataCollectionFrequency
        dataCollectionFrequencyContinually
        dataCollectionFrequencyOther
        dataCollectionFrequencyNote
        qualityReportingStarts
        qualityReportingStartsOther
        qualityReportingStartsNote
        qualityReportingFrequency
        qualityReportingFrequencyContinually
        qualityReportingFrequencyOther
        evaluationApproaches
        evaluationApproachOther
        evaluationApproachNote
        dataNeededForMonitoring
        dataNeededForMonitoringOther
        dataNeededForMonitoringNote
        dataToSendParticicipants
        dataToSendParticicipantsOther
        dataToSendParticicipantsNote
        shareCclfData
        shareCclfDataNote
        modelLearningSystems
        modelLearningSystemsOther
        modelLearningSystemsNote
        anticipatedChallenges
        stakeholders
        stakeholdersOther
        stakeholdersNote
        helpdeskUse
        helpdeskUseNote
        contractorSupport
        contractorSupportOther
        contractorSupportHow
        contractorSupportNote
        benchmarkForPerformance
        benchmarkForPerformanceNote
        computePerformanceScores
        computePerformanceScoresNote
        riskAdjustPerformance
        riskAdjustFeedback
        riskAdjustPayments
        riskAdjustOther
        riskAdjustNote
        appealPerformance
        appealFeedback
        appealPayments
        appealOther
        appealNote
        readyForReviewByUserAccount {
          commonName
        }
        readyForReviewDts
        readyForClearanceByUserAccount {
          commonName
        }
        readyForClearanceDts
        status
      }
      payments {
        id
        payType
        payClaims
        creatingDependenciesBetweenServices
        creatingDependenciesBetweenServicesNote
        needsClaimsDataCollection
        needsClaimsDataCollectionNote
        providingThirdPartyFile
        isContractorAwareTestDataRequirements
        beneficiaryCostSharingLevelAndHandling
        waiveBeneficiaryCostSharingForAnyServices
        waiveBeneficiaryCostSharingServiceSpecification
        waiverOnlyAppliesPartOfPayment
        waiveBeneficiaryCostSharingNote
        payClaimsNote
        payClaimsOther
        shouldAnyProvidersExcludedFFSSystems
        shouldAnyProviderExcludedFFSSystemsNote
        changesMedicarePhysicianFeeSchedule
        changesMedicarePhysicianFeeScheduleNote
        affectsMedicareSecondaryPayerClaims
        affectsMedicareSecondaryPayerClaimsHow
        affectsMedicareSecondaryPayerClaimsNote
        payModelDifferentiation
        willBePaymentAdjustments
        willBePaymentAdjustmentsNote
        expectedCalculationComplexityLevel
        expectedCalculationComplexityLevelNote
        claimsProcessingPrecedence
        claimsProcessingPrecedenceOther
        claimsProcessingPrecedenceNote
        canParticipantsSelectBetweenPaymentMechanisms
        canParticipantsSelectBetweenPaymentMechanismsHow
        canParticipantsSelectBetweenPaymentMechanismsNote
        anticipatedPaymentFrequency
        anticipatedPaymentFrequencyContinually
        anticipatedPaymentFrequencyOther
        anticipatedPaymentFrequencyNote
        fundingSource
        fundingSourcePatientProtectionInfo
        fundingSourceMedicareAInfo
        fundingSourceMedicareBInfo
        fundingSourceOther
        fundingSourceNote
        fundingSourceR
        fundingSourceRPatientProtectionInfo
        fundingSourceRMedicareAInfo
        fundingSourceRMedicareBInfo
        fundingSourceROther
        fundingSourceRNote
        payRecipients
        payRecipientsOtherSpecification
        payRecipientsNote
        payTypeNote
        nonClaimsPayments
        nonClaimsPaymentOther
        nonClaimsPaymentsNote
        paymentCalculationOwner
        numberPaymentsPerPayCycle
        numberPaymentsPerPayCycleNote
        sharedSystemsInvolvedAdditionalClaimPayment
        sharedSystemsInvolvedAdditionalClaimPaymentNote
        planningToUseInnovationPaymentContractor
        planningToUseInnovationPaymentContractorNote
        willRecoverPayments
        willRecoverPaymentsNote
        anticipateReconcilingPaymentsRetrospectively
        anticipateReconcilingPaymentsRetrospectivelyNote
        paymentReconciliationFrequency
        paymentReconciliationFrequencyContinually
        paymentReconciliationFrequencyOther
        paymentReconciliationFrequencyNote
        paymentDemandRecoupmentFrequency
        paymentDemandRecoupmentFrequencyContinually
        paymentDemandRecoupmentFrequencyOther
        paymentDemandRecoupmentFrequencyNote
        paymentStartDate
        paymentStartDateNote
        readyForReviewByUserAccount {
          commonName
        }
        readyForReviewDts
        readyForClearanceByUserAccount {
          commonName
        }
        readyForClearanceDts
        status
      }
      timeline {
        id
        completeICIP
        clearanceStarts
        clearanceEnds
        announced
        applicationsStart
        applicationsEnd
        performancePeriodStarts
        performancePeriodEnds
        highLevelNote
        wrapUpEnds
        readyForReviewByUserAccount {
          id
          commonName
        }
        readyForReviewDts
        readyForClearanceByUserAccount {
          id
          commonName
        }
        readyForClearanceDts
        status
      }
      questionnaires {
        dataExchangeApproach {
          id
          dataToCollectFromParticipants
          dataToCollectFromParticipantsReportsDetails
          dataToCollectFromParticipantsOther
          dataWillNotBeCollectedFromParticipants
          dataToCollectFromParticipantsNote
          dataToSendToParticipants
          dataToSendToParticipantsNote
          doesNeedToMakeMultiPayerDataAvailable
          anticipatedMultiPayerDataAvailabilityUseCase
          doesNeedToMakeMultiPayerDataAvailableNote
          doesNeedToCollectAndAggregateMultiSourceData
          multiSourceDataToCollect
          multiSourceDataToCollectOther
          doesNeedToCollectAndAggregateMultiSourceDataNote
          willImplementNewDataExchangeMethods
          newDataExchangeMethodsDescription
          newDataExchangeMethodsNote
          additionalDataExchangeConsiderationsDescription
          isDataExchangeApproachComplete
          markedCompleteByUserAccount {
            id
            commonName
          }
          markedCompleteDts
          modifiedDts
          createdDts
          status
        }
        iddocQuestionnaire {
          id
          needed
          technicalContactsIdentified
          technicalContactsIdentifiedDetail
          technicalContactsIdentifiedNote
          captureParticipantInfo
          captureParticipantInfoNote
          icdOwner
          draftIcdDueDate
          icdNote
          uatNeeds
          stcNeeds
          testingTimelines
          testingNote
          dataMonitoringFileTypes
          dataMonitoringFileOther
          dataResponseType
          dataResponseFileFrequency
          dataFullTimeOrIncremental
          eftSetUp
          unsolicitedAdjustmentsIncluded
          dataFlowDiagramsNeeded
          produceBenefitEnhancementFiles
          fileNamingConventions
          dataMonitoringNote
          isComplete
          completedByUserAccount {
            id
            commonName
          }
          completedDts
          modifiedDts
          createdDts
          status
          taskListStatus
        }
      }
      mtoMatrix {
        status
        info {
          id
          readyForReviewByUserAccount {
            id
            commonName
          }
          readyForReviewDTS
        }
        categories {
          id
          name
          position
          isUncategorized
          subCategories {
            id
            name
            position
            isUncategorized
          }
        }
        milestones {
          id
          name
          isDraft
          description
          responsibleComponent
          facilitatedBy
          facilitatedByOther
          addedFromMilestoneLibrary
          assignedToPlanCollaborator {
            id
            userAccount {
              id
              commonName
              email
            }
          }
          needBy
          status
          riskIndicator
          notes {
            id
            content
          }
          categories {
            category {
              id
              name
            }
            subCategory {
              id
              name
            }
          }
          solutions {
            id
            name
          }
        }
        solutions {
          id
          name
          solutionType: type
          key
          pocName
          pocEmail
          facilitatedBy
          facilitatedByOther
          neededBy
          status
          riskIndicator
          addedFromSolutionLibrary
          milestones {
            id
            name
          }
        }
      }
      collaborators {
        id
        userAccount {
          id
          commonName
          email
          username
        }
        userID
        teamRoles
        modelPlanID
        createdDts
      }
      discussions {
        id
        isAssessment
        content {
          rawContent
        }
        createdByUserAccount {
          commonName
        }
        userRole
        userRoleDescription
        createdDts
        replies {
          id
          discussionID
          isAssessment
          content {
            rawContent
          }
          createdByUserAccount {
            commonName
          }
          userRole
          userRoleDescription
          createdDts
        }
      }
    }
  }
`);
